import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {assert,canonical,digest,within,executionProfileDigest} from '../lib/core.mjs';
import {runArtifactCommand} from './local-artifacts.mjs';

const roles=['api','gateway','worker'];
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const exactKeys=(x,keys)=>assert(x&&Object.keys(x).every(k=>keys.includes(k)),'Unsupported field in constrained release input');
const id=x=>{assert(typeof x==='string'&&/^[a-z][a-z0-9_]{0,62}$/.test(x),'Invalid SQL identifier');return '"'+x+'"'};
const read=file=>JSON.parse(fs.readFileSync(file,'utf8'));
function save(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});const fd=fs.openSync(file+'.tmp','w',0o600);try{fs.writeSync(fd,canonical(value)+'\n');fs.fsyncSync(fd)}finally{fs.closeSync(fd)}fs.renameSync(file+'.tmp',file);const d=fs.openSync(path.dirname(file),'r');try{fs.fsyncSync(d)}finally{fs.closeSync(d)}}
function privatePath(c,p,isFile=true){assert(path.isAbsolute(p||'')&&within(c.controlDir,fs.realpathSync(p)),'Release authority files must stay in the protected controller directory');const s=fs.statSync(p);assert((isFile?s.isFile():s.isDirectory())&&(s.mode&0o077)===0,'Release authority path must be private');return p}
function rootPath(c,id){assert(/^[a-zA-Z0-9-]{1,100}$/.test(id),'Invalid release operation ID');return path.join(c.controlDir,'aws-release',id+'.json')}
const binding=(q,c)=>digest({id:q.id,kind:q.kind,payload:q.payload,profile:executionProfileDigest(c)});
const arn=(x,service,t)=>typeof x==='string'&&x.startsWith(`arn:aws:${service}:${service==='iam'?'':t.region}:${t.accountId}:`);

export function validateReleaseConfig(config){
 const d=config.local?.deployment;assert(d?.enabled===true&&d?.provider==='aws-ecs-fargate','Select the AWS ECS Fargate release profile');
 assert(path.isAbsolute(d.aws?.command||'')&&/^2\.\d+\.\d+$/.test(d.aws.version),'Pin an absolute AWS CLI v2 executable and exact version');
 for(const k of ['configFile','credentialsFile'])privatePath(config,d.aws[k]);privatePath(config,d.aws.homeDir,false);
 for(const k of ['timeoutSeconds','pollSeconds'])assert(Number.isSafeInteger(d[k])&&d[k]>0,'Finite release deadlines are required');assert(d.timeoutSeconds<=14400&&d.pollSeconds<=30,'Release deadlines exceed this profile');
 assert(/^[a-f0-9]{64}$/.test(d.migration?.sha256)&&typeof d.migration.path==='string'&&!path.isAbsolute(d.migration.path)&&!d.migration.path.split('/').includes('..')&&!/[\0\n:]/.test(d.migration.path),'Pin source-relative migration bytes with SHA256');
 privatePath(config,d.productionApproval?.publicKeyFile);assert(within(config.controlDir,d.productionApproval?.approvalFile||''),'Keep approval file in protected control storage');
 const accounts=[];
 for(const n of ['staging','production']){const t=d.targets?.[n];assert(t&&t.id===config.targets[n]&&/^\d{12}$/.test(t.accountId)&&/^[a-z]{2}-[a-z]+-\d$/.test(t.region)&&/^[A-Za-z0-9_.-]+$/.test(t.profile),'Explicit bound AWS target/account/profile required');accounts.push(t.accountId);
  assert(arn(t.deploymentRoleArn,'iam',t)&&t.deploymentRoleArn.includes(':role/')&&arn(t.clusterArn,'ecs',t)&&t.clusterArn.includes(':cluster/'),'Pin deployment role and ECS cluster');
  assert(/^[A-Za-z0-9_.-]{3,255}$/.test(t.lockTable)&&typeof t.releaseScope==='string'&&t.releaseScope.length<=200&&/^[a-z][a-z0-9-]{0,17}$/.test(t.namePrefix),'Lock table, scope and short resource prefix required');
  assert(Object.keys(t.services||{}).sort().join(',')===roles.slice().sort().join(','),'Exactly api, gateway and worker services are required');
  for(const s of Object.values(t.services)){assert(/^[A-Za-z0-9_-]{1,255}$/.test(s.name)&&/^[A-Za-z0-9_-]{1,255}$/.test(s.containerName)&&arn(s.taskRoleArn,'iam',t)&&arn(s.executionRoleArn,'iam',t)&&arn(s.databaseSecretArn,'secretsmanager',t),'Pin ECS service/container and roles');assert(Array.isArray(s.compatibilityCommand)&&s.compatibilityCommand.length&&s.compatibilityCommand.every(x=>typeof x==='string'&&x.length<=500&&!x.includes('\0')),'A real application schema compatibility command is required');}
  const db=t.database,r=t.rehearsal;assert(db&&arn(db.arn,'rds',t)&&db.arn===`arn:aws:rds:${t.region}:${t.accountId}:cluster:${db.identifier}`&&arn(db.secretArn,'secretsmanager',t)&&arn(db.kmsKeyArn,'kms',t)&&/^[0-9]+\.[0-9]+$/.test(db.engineVersion),'Pin Aurora PostgreSQL cluster, managed secret, KMS key and engine version');id(db.name);
  assert(r&&/^[a-zA-Z0-9-]+$/.test(r.subnetGroup)&&arn(r.taskRoleArn,'iam',t)&&arn(r.executionRoleArn,'iam',t)&&typeof r.logGroup==='string'&&r.logGroup.startsWith('/')&&typeof r.taskFamily==='string'&&/^[a-zA-Z0-9_-]{1,255}$/.test(r.taskFamily)&&Object.values(t.services).every(s=>s.databaseSecretArn!==db.secretArn),'Restricted rehearsal role and separate app credentials required');
  for(const k of ['securityGroupIds','taskSecurityGroupIds','subnetIds'])assert(Array.isArray(r[k])&&r[k].length&&r[k].every(x=>/^(sg|subnet)-[a-f0-9]+$/.test(x)),'Explicit private rehearsal network required');
  assert(Number.isFinite(r.minCapacity)&&r.minCapacity>=0.5&&Number.isFinite(r.maxCapacity)&&r.maxCapacity>=r.minCapacity&&r.maxCapacity<=16,'Bound rehearsal database capacity');
  assert(Array.isArray(t.healthUrls)&&t.healthUrls.length&&t.healthUrls.every(x=>{try{const u=new URL(x);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&u.port===''}catch{return false}}),'Pin HTTPS readiness URLs');
 }
 assert(accounts[0]!==accounts[1],'Staging and production must use separate AWS accounts');return d;
}

// This grammar deliberately cannot run arbitrary SQL or data rewrites.
export function compileMigration(plan){
 exactKeys(plan,['version','id','operations']);assert(plan.version===1&&/^[a-z0-9][a-z0-9_-]{0,79}$/.test(plan.id)&&Array.isArray(plan.operations)&&plan.operations.length<=100,'Invalid additive migration plan');
 const type=x=>{assert(['text','bigint','boolean','timestamptz','uuid','jsonb'].includes(x),'Unsupported column type');return x};
 const statements=[];
 for(const op of plan.operations){
  if(op.kind==='create_table'){exactKeys(op,['kind','table','columns','primaryKey']);assert(Array.isArray(op.columns)&&op.columns.length&&op.columns.length<=50,'New table columns required');const names=new Set();const cols=op.columns.map(c=>{exactKeys(c,['name','type']);assert(!names.has(c.name),'Duplicate column');names.add(c.name);return id(c.name)+' '+type(c.type)});if(op.primaryKey){assert(Array.isArray(op.primaryKey)&&op.primaryKey.length&&op.primaryKey.every(k=>names.has(k)),'Primary key must use new table columns');cols.push('PRIMARY KEY ('+op.primaryKey.map(id).join(', ')+')')}statements.push('CREATE TABLE public.'+id(op.table)+' ('+cols.join(', ')+')','ALTER TABLE public.'+id(op.table)+' ENABLE ROW LEVEL SECURITY','ALTER TABLE public.'+id(op.table)+' FORCE ROW LEVEL SECURITY','REVOKE ALL ON public.'+id(op.table)+' FROM PUBLIC');}
  else if(op.kind==='add_nullable_column'){exactKeys(op,['kind','table','column','type']);statements.push('ALTER TABLE public.'+id(op.table)+' ADD COLUMN '+id(op.column)+' '+type(op.type));}
  else if(op.kind==='create_index'){exactKeys(op,['kind','table','name','columns']);assert(Array.isArray(op.columns)&&op.columns.length&&op.columns.length<=8,'Index columns required');statements.push('CREATE INDEX '+id(op.name)+' ON public.'+id(op.table)+' ('+op.columns.map(id).join(', ')+')');}
  else throw Error('Only additive tables, nullable columns and nonunique indexes are supported');
 }
 return statements;
}
function migrationFromCommit(q,c,d){
 const h=q.payload.executionHead;assert(/^[a-f0-9]{40}$/.test(h),'Exact merged commit required');
 const repo=fs.realpathSync(path.join(c.controlDir,'product.git'));assert(within(c.controlDir,repo),'Protected repository required');
 const opts={env:{PATH:'/usr/bin:/bin',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_TERMINAL_PROMPT:'0'},timeout:30000,maxBuffer:1024*1024};
 const git=args=>execFileSync('/usr/bin/git',['-c','core.hooksPath=/dev/null','--git-dir',repo,...args],opts);
 assert(git(['rev-parse','--verify',h+'^{commit}']).toString().trim()===h,'Merged commit is missing');
 const entry=git(['ls-tree',h,'--',d.migration.path]).toString();assert(/^100(644|755) blob [a-f0-9]{40}\t/.test(entry),'Migration must be a regular file in the checked commit');
 const bytes=git(['show',h+':'+d.migration.path]);assert(sha(bytes)===d.migration.sha256,'Migration bytes differ from the certified configuration');const plan=JSON.parse(bytes);return {plan,statements:compileMigration(plan),sha256:sha(bytes)};
}
function verifyBundle(b,q,c){const {artifactDigest,...body}=b;assert(artifactDigest===digest(body)&&b.executionHead===q.payload.executionHead&&b.provenance?.profileDigest===executionProfileDigest(c),'Artifact source/profile/digest mismatch');assert(Object.keys(b.images||{}).sort().join(',')===roles.slice().sort().join(','),'Incomplete artifact bundle');for(const n of ['staging','production'])for(const role of roles){const t=c.local.deployment.targets[n],i=b.images[role];assert(/^sha256:[a-f0-9]{64}$/.test(i.digest)&&i.uris[n]?.startsWith(`${t.accountId}.dkr.ecr.${t.region}.amazonaws.com/`)&&i.uris[n].endsWith('@'+i.digest),'Target image is not the exact isolated-account digest')}return b}
function context(q,c,deps={}){
 const d=validateReleaseConfig(c),now=deps.now||Date.now,deadline=now()+Math.min(q.timeoutSeconds||d.timeoutSeconds,d.timeoutSeconds)*1000,run=deps.run||runArtifactCommand;
 const env={HOME:d.aws.homeDir,AWS_CONFIG_FILE:d.aws.configFile,AWS_SHARED_CREDENTIALS_FILE:d.aws.credentialsFile,AWS_EC2_METADATA_DISABLED:'true',AWS_MAX_ATTEMPTS:'1',AWS_PAGER:'',AWS_IGNORE_CONFIGURED_ENDPOINT_URLS:'true'};
 const remaining=()=>{const s=Math.floor((deadline-now())/1000);assert(s>0,'Release deadline reached; retain intents and locks for recovery');return s};
 const call=async(t,service,verb,input={})=>{const r=await run(d.aws.command,[service,verb,'--cli-input-json',canonical(input),'--profile',t.profile,'--region',t.region,'--output','json','--no-cli-pager','--no-cli-auto-prompt','--cli-connect-timeout','10','--cli-read-timeout','30'],{env,timeoutSeconds:Math.min(45,remaining()),maxBytes:8*1024*1024});assert(r.exitCode===0,`AWS ${service} ${verb} did not confirm success; reconcile before retrying`);return r.stdout.trim()?JSON.parse(r.stdout):{}};
 const wait=async(fn)=>{for(;;){remaining();const v=await fn();if(v)return v;await(deps.sleep?deps.sleep(d.pollSeconds*1000):new Promise(r=>setTimeout(r,d.pollSeconds*1000)))}};
 return {q,c,d,deps,now,run,env,remaining,call,wait};
}
async function identity(x,t){const v=await x.call(t,'sts','get-caller-identity');const role=t.deploymentRoleArn.split('/').pop();assert(v.Account===t.accountId&&v.Arn?.startsWith(`arn:aws:sts::${t.accountId}:assumed-role/${role}/`)&&v.Arn.split('/').length===3,'Deployment role/account mismatch');return {accountId:v.Account,arn:v.Arn}}
async function service(x,t,s){const r=await x.call(t,'ecs','describe-services',{cluster:t.clusterArn,services:[s.name]});const v=r.services?.[0];assert(!r.failures?.length&&r.services?.length===1&&v.serviceName===s.name&&v.clusterArn===t.clusterArn&&v.status==='ACTIVE'&&v.deploymentController?.type==='ECS'&&v.launchType==='FARGATE'&&Number.isSafeInteger(v.desiredCount)&&v.desiredCount>0&&v.desiredCount<=(s.containerName==='worker'?4:6)&&v.networkConfiguration?.awsvpcConfiguration?.assignPublicIp==='DISABLED','Unsupported or missing private bounded Fargate service');return v}
async function definition(x,t,s,ref){const r=await x.call(t,'ecs','describe-task-definition',{taskDefinition:ref,include:['TAGS']});const v=r.taskDefinition;assert(v?.taskDefinitionArn===ref&&v.taskRoleArn===s.taskRoleArn&&v.executionRoleArn===s.executionRoleArn&&v.networkMode==='awsvpc'&&v.requiresCompatibilities?.includes('FARGATE')&&v.containerDefinitions?.length===1,'Task definition/role binding changed');const k=v.containerDefinitions[0];assert(k.name===s.containerName&&k.user==='10001:10001'&&k.readonlyRootFilesystem===true&&k.essential===true&&/^[A-Za-z0-9._/:\-]+@sha256:[a-f0-9]{64}$/.test(k.image)&&!k.privileged&&(!v.volumes||v.volumes.every(z=>Object.keys(z).length===1&&typeof z.name==='string'))&&k.healthCheck,'Single pinned-image container with health check required');assert(!k.secrets?.some(z=>z.valueFrom.startsWith(t.database.secretArn)),'Application task must never receive the database master secret');return v}
async function database(x,t,identifier=t.database.identifier){const r=await x.call(t,'rds','describe-db-clusters',{DBClusterIdentifier:identifier});assert(r.DBClusters?.length===1,'Expected one Aurora cluster');return r.DBClusters[0]}
function checkDatabase(db,t){assert(db.DBClusterArn===t.database.arn&&db.DBClusterIdentifier===t.database.identifier&&db.Engine==='aurora-postgresql'&&db.EngineVersion===t.database.engineVersion&&db.StorageEncrypted===true&&db.KmsKeyId===t.database.kmsKeyArn&&db.HttpEndpointEnabled===true&&db.MasterUserSecret?.SecretArn===t.database.secretArn&&db.Status==='available','Source Aurora cluster does not match approved encrypted Data API target')}
export async function preflight(c,deps={}){const d=validateReleaseConfig(c),x=context({timeoutSeconds:240},c,deps);const version=await x.run(d.aws.command,['--version'],{env:x.env,timeoutSeconds:10});assert(version.exitCode===0&&version.stdout.startsWith('aws-cli/'+d.aws.version+' '),'AWS CLI version changed');const targets={};for(const n of ['staging','production']){const t=d.targets[n];targets[n]={identity:await identity(x,t)};checkDatabase(await database(x,t),t);const table=await x.call(t,'dynamodb','describe-table',{TableName:t.lockTable});assert(table.Table?.KeySchema?.length===1&&table.Table.KeySchema[0].AttributeName==='release_scope'&&table.Table.KeySchema[0].KeyType==='HASH','Release lock table schema mismatch');for(const role of roles){const s=t.services[role],v=await service(x,t,s);await definition(x,t,s,v.taskDefinition)}}return {verified:true,profile:'aws-ecs-fargate-aurora-additive-v1',targets}}
function mutation(x,op,file){return async(t,label,svc,verb,input,dispatch=x)=>{assert(!op.steps[label],'A mutation was already attempted; use read-only recovery');op.steps[label]={state:'intent',environment:t.id,service:svc,verb,inputDigest:digest(input),input};save(file,op);if(x.q.kind==='production_deploy'){const release=loadRelease(x.q,x.c);const approval=verifyProductionApproval(x.c,release,x.now());assert(approval.digest===op.approvalDigest,'Production approval changed during dispatch')}const result=await dispatch.call(t,svc,verb,input);op.steps[label]={...op.steps[label],state:'confirmed',result};save(file,op);return result}}
async function lock(x,t,release){const r=await x.call(t,'dynamodb','get-item',{TableName:t.lockTable,Key:{release_scope:{S:t.releaseScope}},ConsistentRead:true});assert(r.Item?.owner?.S===release.id&&r.Item?.profile_digest?.S===release.profileDigest,'Release lock ownership is missing or changed')}
async function snapshot(x,t,label,mut){const name=`${t.namePrefix}-${t.environment}-release-${digest(label).slice(0,20)}`;await mut(t,label+'-snapshot','rds','create-db-cluster-snapshot',{DBClusterIdentifier:t.database.identifier,DBClusterSnapshotIdentifier:name,Tags:[{Key:'oxagen:release',Value:label}]});const s=await x.wait(async()=>{const r=await x.call(t,'rds','describe-db-cluster-snapshots',{DBClusterSnapshotIdentifier:name});const v=r.DBClusterSnapshots?.[0];assert(v?.DBClusterIdentifier===t.database.identifier&&v.StorageEncrypted&&v.KmsKeyId===t.database.kmsKeyArn,'Backup source or encryption mismatch');return v.Status==='available'&&v});return {name,arn:s.DBClusterSnapshotArn,createdAt:s.SnapshotCreateTime}}
const schemaSQL="SELECT table_name,column_name,data_type,is_nullable,COALESCE(column_default,'') AS column_default FROM information_schema.columns WHERE table_schema='public' AND table_name <> 'oxagen_release_migrations' ORDER BY table_name,ordinal_position";
async function sql(x,t,db,statement,parameters=[],transactionId){return x.call(t,'rds-data','execute-statement',{resourceArn:db.arn,secretArn:db.secretArn,database:t.database.name,sql:statement,parameters,includeResultMetadata:true,...(transactionId?{transactionId}:{})})}
const rows=r=>{assert(Array.isArray(r.records)&&r.records.every(row=>Array.isArray(row)&&row.every(v=>v&&Object.keys(v).length===1&&(typeof v.stringValue==='string'||typeof v.booleanValue==='boolean'||Number.isSafeInteger(v.longValue)||v.isNull===true))),'Malformed Data API SELECT response');return r.records.map(row=>row.map(v=>v.stringValue??v.longValue??v.booleanValue??null))};
async function schema(x,t,db){const v=rows(await sql(x,t,db,schemaSQL));assert(v.every(row=>row.length===5&&row.every(z=>typeof z==='string')),'Malformed schema metadata');return v}
function preserves(before,after){const map=new Map(after.map(r=>[r[0]+'.'+r[1],r]));assert(before.every(r=>canonical(map.get(r[0]+'.'+r[1]))===canonical(r)),'Existing database columns changed; automatic rollback is unsafe')}
async function migrate(x,t,db,m,release,label,mut){const before=await schema(x,t,db);const begin=await mut(t,label+'-begin','rds-data','begin-transaction',{resourceArn:db.arn,secretArn:db.secretArn,database:t.database.name});const tx=begin.transactionId;assert(typeof tx==='string'&&tx,'Database did not return a transaction');const invoke=(suffix,statement,parameters=[])=>mut(t,label+'-'+suffix,'rds-data','execute-statement',{resourceArn:db.arn,secretArn:db.secretArn,database:t.database.name,transactionId:tx,sql:statement,parameters});
 await invoke('timeouts',"SET LOCAL lock_timeout = '5s'");await invoke('timeout-statement',"SET LOCAL statement_timeout = '25s'");
 await invoke('journal','CREATE TABLE IF NOT EXISTS public.oxagen_release_migrations (digest text NOT NULL, execution_head text NOT NULL, artifact_digest text NOT NULL, applied_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (digest,artifact_digest))');
 await invoke('journal-private','REVOKE ALL ON TABLE public.oxagen_release_migrations FROM PUBLIC');const journalAccess=rows(await sql(x,t,db,"SELECT c.relowner = (SELECT oid FROM pg_roles WHERE rolname = current_user) AND NOT EXISTS (SELECT 1 FROM aclexplode(COALESCE(c.relacl, acldefault('r', c.relowner))) a WHERE a.grantee <> c.relowner AND a.privilege_type IN ('INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='oxagen_release_migrations'",[],tx));assert(journalAccess.length===1&&journalAccess[0][0]===true,'Migration journal must be owned and writable only by the trusted database authority');
 const existing=rows(await sql(x,t,db,'SELECT execution_head,artifact_digest FROM public.oxagen_release_migrations WHERE digest = :digest',[{name:'digest',value:{stringValue:m.sha256}}],tx));
 assert(existing.every(row=>row.length===2&&/^[a-f0-9]{40}$/.test(row[0])&&/^[a-f0-9]{64}$/.test(row[1])),'Malformed migration journal rows');
 if(!existing.length){for(let i=0;i<m.statements.length;i++)await invoke('ddl-'+i,m.statements[i]);}
 if(!existing.some(row=>row[0]===release.executionHead&&row[1]===release.artifactDigest)){await invoke('record','INSERT INTO public.oxagen_release_migrations (digest,execution_head,artifact_digest) VALUES (:digest,:head,:artifact)',[{name:'digest',value:{stringValue:m.sha256}},{name:'head',value:{stringValue:release.executionHead}},{name:'artifact',value:{stringValue:release.artifactDigest}}]);}
 const committed=await mut(t,label+'-commit','rds-data','commit-transaction',{resourceArn:db.arn,secretArn:db.secretArn,transactionId:tx});assert(committed.transactionStatus==='Transaction Committed','Migration commit outcome is unconfirmed');const after=await schema(x,t,db);preserves(before,after);return {before,after,digest:m.sha256};}
const taskFields=['family','taskRoleArn','executionRoleArn','networkMode','containerDefinitions','volumes','placementConstraints','requiresCompatibilities','cpu','memory','pidMode','ipcMode','proxyConfiguration','inferenceAccelerators','ephemeralStorage','runtimePlatform'];
function taskInput(v){return Object.fromEntries(taskFields.filter(k=>v[k]!==undefined).map(k=>[k,structuredClone(v[k])]))}
async function probe(x,t,original,image,db,label,mut){const input={family:t.rehearsal.taskFamily,taskRoleArn:t.rehearsal.taskRoleArn,executionRoleArn:t.rehearsal.executionRoleArn,networkMode:'awsvpc',requiresCompatibilities:['FARGATE'],cpu:original.cpu,memory:original.memory,volumes:[{name:'scratch'}],...(original.runtimePlatform?{runtimePlatform:original.runtimePlatform}:{}),containerDefinitions:[{name:original.containerDefinitions[0].name,image,essential:true,user:'10001:10001',readonlyRootFilesystem:true,linuxParameters:{capabilities:{drop:['ALL']}},mountPoints:[{sourceVolume:'scratch',containerPath:'/tmp',readOnly:false}],command:t.services[label.split(':')[0]].compatibilityCommand,entryPoint:[],environment:[{name:'DB_HOST',value:db.endpoint},{name:'DB_NAME',value:t.database.name},{name:'OXAGEN_SCHEMA_CONTRACT_TEST',value:'1'}],secrets:[{name:'DB_USER',valueFrom:t.services[label.split(':')[0]].databaseSecretArn+':username::'},{name:'DB_PASSWORD',valueFrom:t.services[label.split(':')[0]].databaseSecretArn+':password::'}],logConfiguration:{logDriver:'awslogs',options:{'awslogs-group':t.rehearsal.logGroup,'awslogs-region':t.region,'awslogs-stream-prefix':'schema-check'}}}],tags:[{key:'oxagen:release-probe',value:label}]};const reg=await mut(t,label+'-definition','ecs','register-task-definition',input);const taskDef=reg.taskDefinition?.taskDefinitionArn;assert(taskDef,'Probe task definition registration is uncertain');
 assert(x.remaining()>65,'Insufficient time for a probe plus confirmed cleanup');const probeClock=context({...x.q,timeoutSeconds:x.remaining()-65},x.c,x.deps);
 const started=await mut(t,label+'-run','ecs','run-task',{cluster:t.clusterArn,taskDefinition:taskDef,launchType:'FARGATE',count:1,clientToken:digest(label),startedBy:digest(label).slice(0,32),enableExecuteCommand:false,tags:[{key:'oxagen:release',value:label.split(':')[3]},{key:'oxagen:purpose',value:'compatibility'}],networkConfiguration:{awsvpcConfiguration:{subnets:t.rehearsal.subnetIds,securityGroups:t.rehearsal.taskSecurityGroupIds,assignPublicIp:'DISABLED'}}});assert(!started.failures?.length&&started.tasks?.length===1,'Schema probe did not start exactly one task');const taskArn=started.tasks[0].taskArn;
 let task;try{task=await probeClock.wait(async()=>{const r=await probeClock.call(t,'ecs','describe-tasks',{cluster:t.clusterArn,tasks:[taskArn]});assert(!r.failures?.length&&r.tasks?.length===1&&r.tasks[0].taskArn===taskArn,'Schema probe task cannot be observed');return r.tasks[0].lastStatus==='STOPPED'&&r.tasks[0]});}catch(error){const cleanup=context({...x.q,timeoutSeconds:60},x.c,x.deps);await mut(t,label+'-stop','ecs','stop-task',{cluster:t.clusterArn,task:taskArn,reason:'Oxagen bounded schema probe did not complete'},cleanup);await cleanup.wait(async()=>{const r=await cleanup.call(t,'ecs','describe-tasks',{cluster:t.clusterArn,tasks:[taskArn]});return !r.failures?.length&&r.tasks?.length===1&&r.tasks[0].taskArn===taskArn&&r.tasks[0].lastStatus==='STOPPED'});throw Error('Schema probe failed; its task stop is confirmed, but release and clone remain held: '+error.message)}assert(task.containers?.length===1&&task.containers[0].exitCode===0,'Real application schema compatibility check failed');return {taskArn,taskDefinition:taskDef,image,exitCode:0};}
async function rehearsal(x,t,backup,release,m,mut){const name=`${t.namePrefix}-${t.environment}-rehearsal-${digest(release.id).slice(0,16)}`,label=t.environment+'-rehearsal',r=t.rehearsal;
 await mut(t,label+'-restore','rds','restore-db-cluster-from-snapshot',{DBClusterIdentifier:name,SnapshotIdentifier:backup.arn,Engine:'aurora-postgresql',EngineVersion:t.database.engineVersion,DBSubnetGroupName:r.subnetGroup,VpcSecurityGroupIds:r.securityGroupIds,KmsKeyId:t.database.kmsKeyArn,DeletionProtection:false,PubliclyAccessible:false,ServerlessV2ScalingConfiguration:{MinCapacity:r.minCapacity,MaxCapacity:r.maxCapacity},Tags:[{Key:'oxagen:release',Value:release.id}]});
 await mut(t,label+'-writer','rds','create-db-instance',{DBInstanceIdentifier:name+'-writer',DBClusterIdentifier:name,DBInstanceClass:'db.serverless',Engine:'aurora-postgresql',PubliclyAccessible:false,Tags:[{Key:'oxagen:release',Value:release.id}]});
 await x.wait(async()=>{const v=await database(x,t,name);return v.Status==='available'&&v.DBClusterMembers?.some(z=>z.IsClusterWriter)&&v});
 await mut(t,label+'-secret','rds','modify-db-cluster',{DBClusterIdentifier:name,ManageMasterUserPassword:true,MasterUserSecretKmsKeyId:t.database.kmsKeyArn,ApplyImmediately:true});const clone=await x.wait(async()=>{const v=await database(x,t,name);return v.Status==='available'&&v.MasterUserSecret?.SecretStatus==='active'&&v});
 await mut(t,label+'-http','rds','enable-http-endpoint',{ResourceArn:clone.DBClusterArn});const db={arn:clone.DBClusterArn,secretArn:clone.MasterUserSecret.SecretArn,endpoint:clone.Endpoint};assert(db.arn!==t.database.arn&&db.secretArn!==t.database.secretArn&&clone.StorageEncrypted,'Rehearsal must be a separate encrypted database');const migration=await migrate(x,t,db,m,release,label,mut);const probes=[];for(const which of ['new','old'])for(const role of roles){const old=release.targets[t.environment].previous[role],image=which==='old'?old.image:release.manifest.images[role].uris[t.environment];probes.push(await probe(x,t,old.definition,image,db,role+':'+t.environment+':'+which+':'+release.id,mut));}
 // Delete only the exact clone whose tags and name prove this operation owns it.
 const tags=await x.call(t,'rds','list-tags-for-resource',{ResourceName:clone.DBClusterArn});assert(tags.TagList?.some(v=>v.Key==='oxagen:release'&&v.Value===release.id)&&name.startsWith(t.namePrefix+'-'+t.environment+'-rehearsal-'),'Clone ownership changed; cleanup is blocked');
 await mut(t,label+'-delete-writer','rds','delete-db-instance',{DBInstanceIdentifier:name+'-writer',SkipFinalSnapshot:true});await x.wait(async()=>{const v=await database(x,t,name);assert(Array.isArray(v.DBClusterMembers),'Malformed cluster membership response');return !v.DBClusterMembers.length});await mut(t,label+'-delete-cluster','rds','delete-db-cluster',{DBClusterIdentifier:name,SkipFinalSnapshot:true});await x.wait(async()=>{const all=await x.call(t,'rds','describe-db-clusters',{});assert(Array.isArray(all.DBClusters),'Malformed cluster deletion response');return !all.DBClusters.some(v=>v.DBClusterIdentifier===name)});return {name,backup,migration,probes,cleanupConfirmed:true};}
function loadRelease(q,c){const receipt=q.payload.previousReceipts?.release_preflight||q.payload.receipts?.release_preflight;assert(receipt?.releaseId,'Missing release preflight receipt');const r=read(rootPath(c,'release-'+receipt.releaseId));assert(r.profileDigest===executionProfileDigest(c)&&r.artifactDigest===receipt.artifactDigest&&r.head===q.payload.head&&r.executionHead===q.payload.executionHead,'Release evidence/profile changed');return r}
function target(x,n){return {...x.d.targets[n],environment:n}}
async function checkLockAndSource(x,t,r){await identity(x,t);await lock(x,t,r);checkDatabase(await database(x,t),t)}
export function verifyProductionApproval(config,release,now=Date.now()){const a=config.local.deployment.productionApproval;privatePath(config,a.approvalFile);const doc=read(a.approvalFile);exactKeys(doc,['body','signature']);const {signature,body}=doc;exactKeys(body,['executionHead','artifactDigest','target','releaseId','expiresAt','nonce']);assert(body.executionHead===release.executionHead&&body.artifactDigest===release.artifactDigest&&body.releaseId===release.id&&body.target===config.targets.production&&Number.isFinite(Date.parse(body.expiresAt))&&Date.parse(body.expiresAt)>now&&Date.parse(body.expiresAt)-now<=86400000&&typeof body.nonce==='string'&&body.nonce.length>=16,'Production approval is missing, expired, or bound to another release');const key=crypto.createPublicKey(fs.readFileSync(a.publicKeyFile));assert(key.asymmetricKeyType==='ed25519'&&crypto.verify(null,Buffer.from(canonical(body)),key,Buffer.from(signature||'','base64')),'Production approval signature is invalid');return {digest:digest(doc),expiresAt:body.expiresAt,nonce:body.nonce}}
async function observeHealth(x,t,expected){const facts=[];for(const role of roles){const s=t.services[role],v=await service(x,t,s);if(v.taskDefinition!==expected[role]||v.deployments?.some(z=>z.rolloutState==='FAILED'))return {healthy:false,reason:'Deployment failed or target changed',facts};if(v.deployments?.length!==1||v.deployments[0].rolloutState!=='COMPLETED'||v.runningCount!==v.desiredCount||v.pendingCount!==0)return null;const listed=await x.call(t,'ecs','list-tasks',{cluster:t.clusterArn,serviceName:s.name,desiredStatus:'RUNNING'});if(listed.taskArns?.length!==v.desiredCount)return null;const tasks=await x.call(t,'ecs','describe-tasks',{cluster:t.clusterArn,tasks:listed.taskArns});if(tasks.failures?.length||!Array.isArray(tasks.tasks)||tasks.tasks.length!==listed.taskArns.length||new Set(tasks.tasks.map(z=>z.taskArn)).size!==listed.taskArns.length||tasks.tasks.some(z=>!listed.taskArns.includes(z.taskArn)||z.lastStatus!=='RUNNING'||z.taskDefinitionArn!==expected[role]||z.healthStatus!=='HEALTHY'||z.containers?.length!==1||z.containers[0].name!==s.containerName||z.containers[0].healthStatus!=='HEALTHY'))return null;for(const lb of v.loadBalancers||[]){const health=await x.call(t,'elbv2','describe-target-health',{TargetGroupArn:lb.targetGroupArn});if(!health.TargetHealthDescriptions?.length||health.TargetHealthDescriptions.some(z=>z.TargetHealth?.State!=='healthy'))return null;}facts.push({role,taskDefinition:expected[role],tasks:listed.taskArns});}
 for(const url of t.healthUrls){let ok=false;try{const fn=x.deps.fetch||fetch;const r=await fn(url,{redirect:'error',signal:AbortSignal.timeout(Math.min(10000,x.remaining()*1000))});ok=r.status===200;await r.body?.cancel()}catch{}if(!ok)return {healthy:false,reason:'HTTPS readiness check failed',facts};}return {healthy:true,facts};}
async function deploy(x,t,r,op,file,mut){await checkLockAndSource(x,t,r);if(t.environment==='production'){assert(r.stagingHealthy===true,'Staging health must pass');const approval=verifyProductionApproval(x.c,r,x.now());assert(approval.digest===x.q.payload.previousReceipts?.production_authorize?.approval?.digest,'Deployment requires the exact approved production receipt');op.approvalDigest=approval.digest;save(file,op)}const old=r.targets[t.environment].previous;for(const role of roles){const v=await service(x,t,t.services[role]);assert(v.taskDefinition===old[role].taskDefinition&&v.runningCount===v.desiredCount&&v.pendingCount===0&&v.deployments?.length===1&&v.deployments[0].rolloutState==='COMPLETED','Service drifted or is not stable; requalification required')}
 const baseline=await observeHealth(x,t,Object.fromEntries(roles.map(role=>[role,old[role].taskDefinition])));assert(baseline?.healthy===true,'Old deployment health is not confirmed');const backup=await snapshot(x,t,op.id,mut);const migration=await migrate(x,t,{arn:t.database.arn,secretArn:t.database.secretArn},r.migration,r,op.id+'-migration',mut);r.targets[t.environment].deployment={backup,migration,definitions:{}};save(rootPath(x.c,'release-'+r.id),r);
 for(const role of roles){await lock(x,t,r);const s=t.services[role],v=await service(x,t,s);assert(v.taskDefinition===old[role].taskDefinition&&v.runningCount===v.desiredCount&&v.pendingCount===0&&v.deployments?.length===1&&v.deployments[0].rolloutState==='COMPLETED','Service changed or became unstable before update');const input=taskInput(old[role].definition);input.containerDefinitions[0].image=r.manifest.images[role].uris[t.environment];input.tags=[{key:'oxagen:release',value:r.id},{key:'oxagen:artifact',value:r.artifactDigest}];const reg=await mut(t,role+'-register','ecs','register-task-definition',input);const ref=reg.taskDefinition?.taskDefinitionArn;assert(ref,'Task registration was not confirmed');r.targets[t.environment].deployment.definitions[role]=ref;save(rootPath(x.c,'release-'+r.id),r);await mut(t,role+'-update','ecs','update-service',{cluster:t.clusterArn,service:s.name,taskDefinition:ref,deploymentConfiguration:{deploymentCircuitBreaker:{enable:true,rollback:false}}});}
 return {target:t.id,artifactDigest:r.artifactDigest,executionHead:r.executionHead,taskDefinitions:r.targets[t.environment].deployment.definitions,backup,migrationDigest:r.migration.sha256};}
async function releaseLocks(x,r,op,file,mut,out){op.terminalOutcome=out;save(file,op);for(const n of ['staging','production']){const t=target(x,n);await lock(x,t,r);await mut(t,n+'-unlock','dynamodb','delete-item',{TableName:t.lockTable,Key:{release_scope:{S:t.releaseScope}},ConditionExpression:'#owner = :owner AND profile_digest = :profile',ExpressionAttributeNames:{'#owner':'owner'},ExpressionAttributeValues:{':owner':{S:r.id},':profile':{S:r.profileDigest}}})}r.finalized=true;save(rootPath(x.c,'release-'+r.id),r);}
export async function execute(q,c,deps={}){
 assert(q.maxCostCents===0,'AWS infrastructure charges are not model USD; configure separate AWS spending controls');const x=context(q,c,deps),file=rootPath(c,q.id),bind=binding(q,c);if(fs.existsSync(file)){const old=read(file);assert(old.binding===bind,'Release request/profile changed');assert(old.result,'An interrupted operation must be reconciled, never repeated');return old.result}
 const op={id:q.id,kind:q.kind,binding:bind,steps:{},startedAt:new Date(x.now()).toISOString()};save(file,op);const mut=mutation(x,op,file);let out;
 if(q.kind==='release_preflight'){
  assert(q.payload.previousReceipts?.post_merge_ci?.checkedHead===q.payload.executionHead&&q.payload.previousReceipts.post_merge_ci.requiredChecksPassed===true,'Exact merged-head CI is required');const migration=migrationFromCommit(q,c,x.d);const build=deps.buildArtifact||(await import('./local-artifacts.mjs')).build;const manifest=verifyBundle(await build(q,c,deps),q,c);const r={id:q.id,head:q.payload.head,executionHead:q.payload.executionHead,profileDigest:executionProfileDigest(c),manifest,artifactDigest:manifest.artifactDigest,migration,targets:{}};save(rootPath(c,'release-'+r.id),r);
  for(const n of ['staging','production']){const t=target(x,n);await identity(x,t);checkDatabase(await database(x,t),t);await mut(t,n+'-lock','dynamodb','put-item',{TableName:t.lockTable,Item:{release_scope:{S:t.releaseScope},owner:{S:r.id},profile_digest:{S:r.profileDigest}},ConditionExpression:'attribute_not_exists(release_scope)'});r.targets[n]={previous:{}};for(const role of roles){const s=t.services[role],v=await service(x,t,s);assert(v.runningCount===v.desiredCount&&v.pendingCount===0&&v.deployments?.length===1&&v.deployments[0].rolloutState==='COMPLETED','Rehearsal requires a stable service baseline');const def=await definition(x,t,s,v.taskDefinition);r.targets[n].previous[role]={taskDefinition:v.taskDefinition,image:def.containerDefinitions[0].image,definition:def};}const baseline=await observeHealth(x,t,Object.fromEntries(roles.map(role=>[role,r.targets[n].previous[role].taskDefinition])));assert(baseline?.healthy===true,'Initial old deployment health is not confirmed');r.targets[n].baseline=baseline;save(rootPath(c,'release-'+r.id),r);const backup=await snapshot(x,t,n+'-'+r.id,mut);r.targets[n].rehearsal=await rehearsal(x,t,backup,r,migration,mut);save(rootPath(c,'release-'+r.id),r);}
  out={releaseId:r.id,executionHead:r.executionHead,artifactDigest:r.artifactDigest,manifest,backupVerified:true,migrationsRehearsed:true,rollbackReady:true};
 }else{const r=loadRelease(q,c),saveRelease=()=>save(rootPath(c,'release-'+r.id),r);op.releaseId=r.id;save(file,op);
  if(q.kind==='production_authorize'){assert(r.stagingHealthy===true,'Staging must be healthy');out={authorized:true,approval:verifyProductionApproval(c,r,x.now()),target:c.targets.production,artifactDigest:r.artifactDigest,releaseId:r.id,executionHead:r.executionHead};}
  else if(['staging_deploy','production_deploy'].includes(q.kind))out=await deploy(x,target(x,q.kind.split('_')[0]),r,op,file,mut);
  else if(['staging_health','production_health'].includes(q.kind)){const n=q.kind.split('_')[0],t=target(x,n);await checkLockAndSource(x,t,r);const expected=r.targets[n].deployment?.definitions;assert(expected&&roles.every(k=>expected[k]),'All service update receipts are required');let health;try{health=await x.wait(()=>observeHealth(x,t,expected))}catch(error){throw Error('Health evidence is incomplete; retain deployment and lock for reconciliation: '+error.message)}if(health.healthy){r[n+'Healthy']=true;saveRelease()}out={...health,target:t.id,artifactDigest:r.artifactDigest,executionHead:r.executionHead};}
  else if(q.kind==='rollback'){const failed=q.payload.failedHealth;assert(failed?.healthy===false,'Rollback requires a confirmed failed health receipt');const n=failed.target===c.targets.production?'production':failed.target===c.targets.staging?'staging':null;assert(n,'Failed target mismatch');const t=target(x,n);await checkLockAndSource(x,t,r);const state=r.targets[n];assert(state.rehearsal?.probes?.length===6&&state.rehearsal.probes.every(p=>p.exitCode===0),'Old/new application compatibility proof is missing');preserves(state.deployment.migration.after,await schema(x,t,{arn:t.database.arn,secretArn:t.database.secretArn}));const restored={};for(const role of roles){const current=await service(x,t,t.services[role]);assert(current.taskDefinition===state.deployment.definitions[role],'Cannot roll back a service changed by another actor');await mut(t,role+'-rollback','ecs','update-service',{cluster:t.clusterArn,service:t.services[role].name,taskDefinition:state.previous[role].taskDefinition,deploymentConfiguration:{deploymentCircuitBreaker:{enable:true,rollback:false}}});restored[role]=state.previous[role].taskDefinition;}const health=await x.wait(()=>observeHealth(x,t,restored));assert(health.healthy,'Rollback health did not pass; retain lock and stop');out={authorized:true,restored:true,healthy:true,target:t.id,restoredArtifactDigest:digest(Object.fromEntries(roles.map(k=>[k,state.previous[k].image]))),taskDefinitions:restored,schemaRetained:true,executionHead:r.executionHead};}
  else throw Error('Unsupported AWS release operation');
  if(q.kind==='production_health'&&out.healthy===true||q.kind==='rollback')await releaseLocks(x,r,op,file,mut,out);
 }
 const result={status:'succeeded',operationId:q.id,costCents:0,head:q.payload.head,...out};op.result=result;save(file,op);return result;
}

// Reconciliation never sends writes. A partial operation stays blocked even if a
// retry would probably work: AWS cannot prove that an unobserved write had no effect.
export async function reconcile(q,c,deps={}){
 const file=rootPath(c,q.id);assert(fs.existsSync(file),'Release startup was not recorded');const op=read(file);assert(op.binding===binding(q,c),'Release recovery request/profile changed');if(op.result)return {status:'succeeded',operationId:q.id,completedReceipt:op.result};
 const x=context(q,c,deps);
 if(q.kind==='production_authorize'){const r=loadRelease(q,c);assert(r.stagingHealthy===true,'Staging must be healthy');const result={status:'succeeded',operationId:q.id,costCents:0,head:q.payload.head,executionHead:r.executionHead,target:c.targets.production,artifactDigest:r.artifactDigest,releaseId:r.id,authorized:true,approval:verifyProductionApproval(c,r,x.now())};op.result=result;save(file,op);return {status:'succeeded',operationId:q.id,completedReceipt:result};}
 if(op.terminalOutcome){const r=loadRelease(q,c);for(const n of ['staging','production']){const t=target(x,n);await identity(x,t);assert(op.steps[n+'-unlock'],'Lock release was not dispatched');const lock=await x.call(t,'dynamodb','get-item',{TableName:t.lockTable,Key:{release_scope:{S:t.releaseScope}},ConsistentRead:true});assert(!lock.Item,'A final lock still exists; reviewed cleanup is required')}const result={status:'succeeded',operationId:q.id,costCents:0,head:q.payload.head,...op.terminalOutcome,recovered:true};op.result=result;save(file,op);return {status:'succeeded',operationId:q.id,completedReceipt:result};}
 if(['staging_deploy','production_deploy'].includes(q.kind)){const r=loadRelease(q,c),n=q.kind.split('_')[0],t=target(x,n),state=r.targets[n];await checkLockAndSource(x,t,r);assert(roles.every(role=>state.deployment?.definitions?.[role]),'Partial deployment definitions; manual recovery required');for(const role of roles){const step=op.steps[role+'-update'];assert(step,'Service update was never dispatched');const v=await service(x,t,t.services[role]);assert(v.taskDefinition===state.deployment.definitions[role],'AWS does not show the exact recorded deployment');}const rowsFound=rows(await sql(x,t,{arn:t.database.arn,secretArn:t.database.secretArn},'SELECT execution_head,artifact_digest FROM public.oxagen_release_migrations WHERE digest = :digest AND artifact_digest = :artifact',[{name:'digest',value:{stringValue:r.migration.sha256}},{name:'artifact',value:{stringValue:r.artifactDigest}}]));assert(rowsFound.length===1&&rowsFound[0][0]===r.executionHead&&rowsFound[0][1]===r.artifactDigest,'Migration commit is unconfirmed');const result={status:'succeeded',operationId:q.id,costCents:0,head:q.payload.head,executionHead:r.executionHead,target:t.id,artifactDigest:r.artifactDigest,taskDefinitions:state.deployment.definitions,backup:state.deployment.backup,migrationDigest:r.migration.sha256,recovered:true};op.result=result;save(file,op);return {status:'succeeded',operationId:q.id,completedReceipt:result};}
 throw Error('Release operation remains uncertain or partial. Retain locks and inspect durable intents; automatic repeat is disabled.');
}
