import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {spawn} from 'node:child_process';
import {assert,canonical,digest,within} from '../lib/core.mjs';

const SHA=/^[0-9a-f]{40}$/;
const opKinds=new Set(['pull_request','ci','merge','post_merge_ci']);
const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
function durable(file,value){const tmp=file+'.tmp';const fd=fs.openSync(tmp,'w',0o600);try{fs.writeSync(fd,canonical(value));fs.fsyncSync(fd)}finally{fs.closeSync(fd)}fs.renameSync(tmp,file);const dir=fs.openSync(path.dirname(file),'r');try{fs.fsyncSync(dir)}finally{fs.closeSync(dir)}}
export async function runCommand(command,args,{env,input='',timeoutSeconds=60}={}){
 return new Promise((resolve,reject)=>{let out='',err='',size=0,failed=false;const child=spawn(command,args,{env,stdio:['pipe','pipe','pipe'],shell:false,detached:false});const stop=()=>{try{child.kill('SIGKILL')}catch{}};const timer=setTimeout(()=>{failed=true;stop()},timeoutSeconds*1000);child.stdout.setEncoding('utf8');child.stdout.on('data',b=>{size+=b.length;if(size>16*1024*1024){failed=true;stop()}else out+=b});child.stderr.setEncoding('utf8');child.stderr.on('data',b=>{err=(err+b).slice(-4096)});child.on('error',()=>{clearTimeout(timer);reject(new Error('Protected GitHub command failed'))});child.on('close',code=>{clearTimeout(timer);if(failed||code!==0){const error=new Error('Protected GitHub command failed or timed out; wrapper process-group cleanup must precede reconciliation');error.childStopUnproved=true;error.stderrTail=err;reject(error)}else resolve(out)});child.stdin.on('error',()=>{});child.stdin.end(input)});
}
function configuration(config){
 const g=config.local?.github||config.github;assert(g&&path.isAbsolute(config.controlDir),'Protected GitHub configuration required');
 assert(fs.realpathSync(config.controlDir)===path.resolve(config.controlDir),'Control root must be its canonical path');
 assert(!config.workRoot||!within(config.workRoot,config.controlDir),'Control root cannot be agent-writable');
 assert(/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(g.repository),'Pin owner/repository');
 assert(Number.isSafeInteger(g.repositoryId)&&g.repositoryId>0,'Pin numeric GitHub repository ID');
 assert(/^[A-Za-z0-9.-]+$/.test(g.hostname||'github.com'),'Invalid GitHub host');
 assert(typeof g.defaultBranch==='string'&&g.defaultBranch.length&&g.defaultBranch.length<200,'Explicit default branch required');
 assert(['merge','squash'].includes(g.mergeMethod),'Only proved merge or squash strategies are supported');
 for(const key of ['requiredChecks','postMergeRequiredChecks']){assert(Array.isArray(g[key])&&g[key].length>0,'At least one explicitly pinned '+key+' is required');const seen=new Set();for(const c of g[key]){assert(['check_run','status'].includes(c.kind)&&typeof c.name==='string'&&c.name.length>0,'Named checks required');assert(Number.isSafeInteger(c.kind==='check_run'?c.appId:c.creatorId)&&(c.kind==='check_run'?c.appId:c.creatorId)>0,'Pin each CI producer identity');const k=c.kind+':'+c.name;assert(!seen.has(k),'Duplicate CI check');seen.add(k)}}
 for(const k of ['gitPath','ghPath'])assert(path.isAbsolute(g[k])&&(!config.workRoot||!within(config.workRoot,g[k])),'Trusted absolute executable required');
 assert(path.isAbsolute(g.authConfigDir)&&within(config.controlDir,fs.realpathSync(g.authConfigDir)),'gh credentials must stay in the protected control root');
 assert((fs.statSync(config.controlDir).mode&0o022)===0&&(fs.statSync(g.authConfigDir).mode&0o077)===0,'Protect controller and gh credential directory permissions');
 for(const tokenFile of [g.tokenFile,g.policyTokenFile].filter(Boolean)){assert(path.isAbsolute(tokenFile),'Token file must be absolute');const stat=fs.lstatSync(tokenFile);assert(stat.isFile()&&!stat.isSymbolicLink()&&within(config.controlDir,fs.realpathSync(tokenFile)),'Token must be a regular protected control-root file');assert((stat.mode&0o077)===0&&(!process.getuid||stat.uid===process.getuid()),'Token file must be private and owned by the controller account')}
 if(config.targets?.repository)assert(config.targets.repository===g.repository,'Engine repository target differs from pinned GitHub repository');
 return {...g,hostname:g.hostname||'github.com',apiVersion:g.apiVersion||'2022-11-28',repoDir:path.join(config.controlDir,'product.git'),stateDir:path.join(config.controlDir,'github-operations'),remoteUrl:`https://${g.hostname||'github.com'}/${g.repository}.git`};
}
function acquireLock(lock,reconcileOnly){
 try{fs.mkdirSync(lock,{mode:0o700})}catch(e){
  assert(e.code==='EEXIST'&&reconcileOnly,'Operation lock exists; only read-only reconciliation may recover it');
  const ownerPath=path.join(lock,'owner.json');assert(fs.existsSync(ownerPath),'Incomplete operation lock needs operator repair under the controller lock');
  const owner=JSON.parse(fs.readFileSync(ownerPath,'utf8'));assert(owner.hostname===os.hostname()&&Number.isSafeInteger(owner.pid)&&owner.pid>0,'Cannot prove lock owner belongs to this host');
  let dead=false;try{process.kill(owner.pid,0)}catch(error){dead=error.code==='ESRCH'}assert(dead,'Operation lock owner is alive or cannot be checked');
  const recovery=fs.openSync(path.join(lock,'recovery.claim'),'wx',0o600);try{fs.writeSync(recovery,canonical({pid:process.pid,hostname:os.hostname()}));fs.fsyncSync(recovery)}finally{fs.closeSync(recovery)}
  assert(canonical(JSON.parse(fs.readFileSync(ownerPath,'utf8')))===canonical(owner),'Lock owner changed during recovery');
  fs.rmSync(lock,{recursive:true});fs.mkdirSync(lock,{mode:0o700});
 }
 durable(path.join(lock,'owner.json'),{pid:process.pid,hostname:os.hostname(),createdAt:new Date().toISOString()});
}
export function createAdapter(config,{command=runCommand,sleep=ms=>new Promise(r=>setTimeout(r,ms))}={}){
 const g=configuration(config);const env={PATH:'/usr/bin:/bin',GH_CONFIG_DIR:g.authConfigDir,GH_HOST:g.hostname,GH_PROMPT_DISABLED:'1',GIT_TERMINAL_PROMPT:'0',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_SYSTEM:'/dev/null',LC_ALL:'C'};
 const tokenKey=g.hostname==='github.com'||g.hostname.endsWith('.ghe.com')?'GH_TOKEN':'GH_ENTERPRISE_TOKEN';
 const readToken=file=>{const token=fs.readFileSync(file,'utf8').trim();assert(token.length>10&&token.length<=4096&&!/\s/.test(token),'Invalid protected token file');return token};
 if(g.tokenFile)env[tokenKey]=readToken(g.tokenFile);
 const policyEnv=g.policyTokenFile?{...env,[tokenKey]:readToken(g.policyTokenFile)}:env;
 // API calls stay short. Git transfers get their own bound because a real repository over a slow link
 // exceeds any API-sized timeout, and a timed-out transfer becomes an unknown that reconcile cannot clear.
 const apiTimeout=Math.min(g.commandTimeoutSeconds||30,120),gitTimeout=Math.min(g.gitTimeoutSeconds||600,3600);
 const invoke=(bin,args,input='',commandEnv=env,timeoutSeconds=apiTimeout)=>command(bin,args,{env:commandEnv,input,timeoutSeconds});
 const git=(args)=>invoke(g.gitPath,['-c','core.hooksPath=/dev/null','-c','credential.helper=','-c',`credential.https://${g.hostname}.helper=!${quote(g.ghPath)} auth git-credential`,'--git-dir',g.repoDir,...args],'',env,gitTimeout).then(s=>s.trim());
 async function api(endpoint,{method='GET',body,paginate=false,policy=false}={}){assert(endpoint.startsWith('/repos/'+g.repository)||endpoint==='/user','API target escaped pinned repository');if(policy)assert(method==='GET'&&(endpoint===root+'/branches/'+encodeURIComponent(g.defaultBranch)+'/protection'||endpoint.startsWith(root+'/collaborators/')&&endpoint.endsWith('/permission')),'Policy credential is restricted to protection and permission reads');const a=['api','--hostname',g.hostname,'--method',method,'-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: '+g.apiVersion,endpoint];if(paginate)a.push('--paginate','--slurp');if(body!==undefined)a.push('--input','-');const text=await invoke(g.ghPath,a,body===undefined?'':canonical(body),policy?policyEnv:env);try{return JSON.parse(text)}catch{throw new Error('GitHub returned invalid structured data; reconcile uncertain writes')}}
 const root='/repos/'+g.repository;
 const notCancelled=()=>assert(!fs.existsSync(path.join(config.controlDir,'CANCEL')),'Controller cancellation requested; no new GitHub operation');
 async function identity(){const r=await api(root);assert(r.id===g.repositoryId&&r.full_name.toLowerCase()===g.repository.toLowerCase()&&r.default_branch===g.defaultBranch&&!r.archived&&!r.disabled,'Pinned repository identity/default branch changed');return r}
 async function remoteHead(){const r=await api(root+'/git/ref/heads/'+encodeURIComponent(g.defaultBranch));assert(r.object?.type==='commit'&&SHA.test(r.object.sha),'Existing initialized default branch required');return r.object.sha}
 async function fetchDefault(){await git(['fetch','--no-tags',g.remoteUrl,'+refs/heads/'+g.defaultBranch+':refs/remotes/oxagen/default']);const sha=await git(['rev-parse','refs/remotes/oxagen/default']);assert(SHA.test(sha),'Invalid fetched base');return sha}
 async function initializeRepository(){await identity();await invoke(g.gitPath,['check-ref-format','refs/heads/'+g.defaultBranch]);if(!fs.existsSync(g.repoDir)){await invoke(g.gitPath,['-c','core.hooksPath=/dev/null','init','--bare',g.repoDir]);await git(['remote','add','origin',g.remoteUrl])}assert(await git(['rev-parse','--is-bare-repository'])==='true','Protected product.git must be bare');assert(within(config.controlDir,fs.realpathSync(g.repoDir)),'Bare Git metadata escaped protected root');const remote=await git(['remote','get-url','origin']);assert(remote===g.remoteUrl,'Pinned Git remote changed');const head=await fetchDefault();assert(head===await remoteHead(),'Remote moved during initialization; retry read-only preflight');const refs=await git(['for-each-ref','--format=%(refname)','refs/heads/main']);if(!refs)await git(['update-ref','refs/heads/main',head]);return {repository:g.repository,repositoryId:g.repositoryId,defaultBranch:g.defaultBranch,head}}
 async function mergeProtection(){
  const [repo,user]=await Promise.all([identity(),api('/user')]);
  assert(user.type==='User'&&user.site_admin===false&&Number.isSafeInteger(user.id)&&typeof user.login==='string','A proved ordinary GitHub user identity is required for this merge profile');
  assert(repo.permissions?.admin===false&&repo.permissions?.push===true,'Merge account must have write access without repository admin rights');
  const [permission,protection]=await Promise.all([api(root+'/collaborators/'+encodeURIComponent(user.login)+'/permission',{policy:true}),api(root+'/branches/'+encodeURIComponent(g.defaultBranch)+'/protection',{policy:true})]);
  assert(permission.user?.id===user.id&&permission.permission==='write'&&permission.role_name==='write','Custom, admin, app or ambiguous repository roles are unsupported for live merge');
  assert(protection.required_status_checks?.strict===true&&protection.enforce_admins?.enabled===true,'Classic protection must require up-to-date branches and enforce checks for administrators');
  assert(protection.allow_force_pushes?.enabled===false&&protection.allow_deletions?.enabled===false,'Default branch must forbid force pushes and deletion');
  const bypass=protection.required_pull_request_reviews?.bypass_pull_request_allowances;
  assert(!bypass||['users','teams','apps'].every(k=>Array.isArray(bypass[k])&&bypass[k].length===0),'Bypass allowances are unsupported for this merge profile');
  const checks=protection.required_status_checks.checks;assert(Array.isArray(checks),'App-bound required check identities must be observable');
  for(const required of g.requiredChecks)assert(Number.isSafeInteger(required.appId)&&required.appId>0&&checks.some(c=>c.context===required.name&&c.app_id===required.appId),'Required CI is not covered by an exact server-enforced context/app binding');
  return {profile:'classic-strict-standard-writer',verified:true,userId:user.id,repositoryId:g.repositoryId,defaultBranch:g.defaultBranch,strict:true,enforceAdmins:true,policyDigest:digest(protection),requiredChecks:g.requiredChecks,observedAt:new Date().toISOString()};
 }
 async function preflight(){const r=await initializeRepository();const protection=await mergeProtection();await invoke(g.ghPath,['auth','status','--hostname',g.hostname]);return {repository:r,mergeProtection:protection,githubConfigured:true,credentialsOutsideAgents:true,gitMetadataProtected:true,hookTargetsPinned:true,requiredChecks:g.requiredChecks,postMergeRequiredChecks:g.postMergeRequiredChecks,mergeMethod:g.mergeMethod}}
 function reviewed(q){assert(q&&typeof q.id==='string'&&q.id.length>0&&opKinds.has(q.kind),'Unsupported GitHub operation');const p=q.payload;assert(SHA.test(p?.head)&&SHA.test(p?.base),'Exact reviewed head and base required');assert(p.phase!=='design','Design artifacts stay local until certification');assert(p.targets?.repository===g.repository,'Request repository target is not pinned repository');assert(p.review?.head===p.head&&p.review.verdict==='pass'&&p.review.findings?.length===0&&p.review.sessionId,'Fresh clean review required');return p}
 async function candidate(p){await identity();assert(await git(['remote','get-url','origin'])===g.remoteUrl,'Pinned Git remote changed');assert(await git(['rev-parse',p.head+'^{commit}'])===p.head,'Reviewed commit missing');await git(['merge-base','--is-ancestor',p.base,p.head]);return git(['rev-parse',p.head+'^{tree}'])}
 const branchFor=(q)=>'oxagen/'+String(q.batchId).replace(/[^a-z0-9-]/g,'-')+'/'+q.payload.head;
 const marker=q=>'<!-- oxagen-reviewed-head:'+q.payload.head+' -->';
 function prRef(pr){return {number:pr.number,url:pr.html_url,branch:pr.head.ref,head:pr.head.sha,base:pr.base.ref,repository:g.repository}}
 function verifyPR(pr,p,branch){assert(Number.isSafeInteger(pr.number)&&pr.number>0&&pr.head?.repo?.id===g.repositoryId&&pr.base?.repo?.id===g.repositoryId&&pr.head.sha===p.head&&pr.base.ref===g.defaultBranch,'PR identity/head/base mismatch');if(branch)assert(pr.head.ref===branch,'PR branch mismatch');assert(pr.html_url===`https://${g.hostname}/${g.repository}/pull/${pr.number}`,'Unexpected PR URL');return pr}
 async function lookup(q){const p=q.payload,branch=branchFor(q);const pages=await api(root+'/pulls?state=all&head='+encodeURIComponent(g.repository.split('/')[0]+':'+branch)+'&base='+encodeURIComponent(g.defaultBranch)+'&per_page=100',{paginate:true});const matches=pages.flat().filter(x=>x.head?.ref===branch);assert(matches.length<=1,'Multiple matching pull requests require manual reconciliation');return matches[0]?verifyPR(await api(root+'/pulls/'+matches[0].number),p,branch):null}
 async function loadPR(q){const p=q.payload;if(p.pr?.number){assert(Number.isSafeInteger(p.pr.number)&&p.pr.number>0,'Invalid PR number');return verifyPR(await api(root+'/pulls/'+p.pr.number),p,branchFor(q))}const pr=await lookup(q);assert(pr,'Expected controlled PR not found');return pr}
 async function checks(sha,required,allowCancelled=false){if(!allowCancelled)notCancelled();assert(SHA.test(sha),'Exact CI commit required');const [cp,sp]=await Promise.all([api(root+'/commits/'+sha+'/check-runs?filter=all&per_page=100',{paginate:true}),api(root+'/commits/'+sha+'/statuses?per_page=100',{paginate:true})]);const runs=cp.flatMap(x=>x.check_runs),statuses=sp.flat();const results=required.map(c=>{if(c.kind==='check_run'){const matches=runs.filter(x=>x.name===c.name&&x.app?.id===c.appId&&x.head_sha===sha).sort((a,b)=>b.id-a.id);const latest=matches[0];return {kind:c.kind,name:c.name,producerId:c.appId,id:latest?.id??null,state:latest?.status??'missing',conclusion:latest?.conclusion??null,passed:latest?.status==='completed'&&latest.conclusion==='success'}}const latest=statuses.filter(x=>x.context===c.name).sort((a,b)=>b.id-a.id)[0];return {kind:c.kind,name:c.name,producerId:c.creatorId,observedProducerId:latest?.creator?.id??null,id:latest?.id??null,state:latest?.state??'missing',passed:latest?.state==='success'&&latest.creator?.id===c.creatorId}});return {checkedHead:sha,requiredChecksPassed:results.length>0&&results.every(x=>x.passed),checks:results}}
 // CI wait honors the configured ciWaitSeconds up to the operation deadline the engine passed, minus a
 // margin so the hook still returns a receipt. Polling backs off from one second to one minute with jitter
 // so a long CI run does not burn the API rate limit.
 async function waitChecks(sha,required,allowCancelled=false,operationSeconds){const budget=Math.min(g.ciWaitSeconds??30,Math.max(10,(operationSeconds??60)-30));const deadline=Date.now()+budget*1000;let result,delay=1000;do{result=await checks(sha,required,allowCancelled);if(result.requiredChecksPassed||result.checks.some(x=>x.kind==='check_run'?x.state==='completed'&&!x.passed:['failure','error'].includes(x.state)||(x.state==='success'&&x.observedProducerId!==x.producerId))||Date.now()>=deadline)return result;await sleep(Math.min(delay,Math.max(0,deadline-Date.now())));delay=Math.min(delay*2,60000)+Math.floor(Math.random()*1000)}while(true)}
 async function mergeProof(q,pr,expectedTree){const p=q.payload;assert(pr.merged===true&&SHA.test(pr.merge_commit_sha),'No confirmed merged commit');const mergedHead=pr.merge_commit_sha;await fetchDefault();await git(['fetch','--no-tags',g.remoteUrl,mergedHead]);assert(await git(['rev-parse',mergedHead+'^{commit}'])===mergedHead,'Merged commit missing');const tree=await git(['rev-parse',mergedHead+'^{tree}']);const parents=(await git(['show','-s','--format=%P',mergedHead])).split(' ').filter(Boolean);assert(tree===expectedTree,'Actual merged tree differs from reviewed candidate; fresh review required');assert(g.mergeMethod==='squash'?parents.length===1&&parents[0]===p.base:parents.length===2&&parents[0]===p.base&&parents[1]===p.head,'Default branch changed or merge provenance differs; fresh review required');await git(['merge-base','--is-ancestor',mergedHead,'refs/remotes/oxagen/default']);return {merged:true,mergedHead,reviewedHead:p.head,reviewedBase:p.base,checkedBase:p.base,baseMatched:true,baseCompareAndSwap:false,mergeStrategy:g.mergeMethod,mergedTree:tree,reviewedTree:expectedTree,treeMatchesReviewed:true,provenanceVerified:true,parents,pr:prRef(pr)}}
 const receipt=(q,data)=>({status:'succeeded',operationId:q.id,opId:q.id,costCents:0,head:q.payload.head,base:q.payload.base,repository:g.repository,repositoryId:g.repositoryId,...data});
 function ciFailure(q,result,reason){const terminalFailure=result.checks.some(x=>x.kind==='check_run'?x.state==='completed'&&!x.passed:['failure','error'].includes(x.state)||(x.state==='success'&&x.observedProducerId!==x.producerId));return {...receipt(q,result),status:terminalFailure?'failed':'unknown',reason:reason+(terminalFailure?'; repair is required':'; read-only reconciliation required'),noExternalEffect:true,allChildrenStopped:true}}
 async function perform(q,state,save,reconcileOnly){if(!reconcileOnly)notCancelled();const p=reviewed(q),tree=await candidate(p);if(q.kind==='pull_request'){const found=await lookup(q);if(found){assert(await remoteHead()===p.base,'Remote base moved; obtain fresh review before adopting PR');assert(!found.merged&&found.state==='open'&&found.body?.includes(marker(q)),'Existing PR is not an adoptable controlled open request');return receipt(q,{pr:prRef(found),reconciled:true})}if(reconcileOnly)return {status:'unknown',operationId:q.id,opId:q.id,costCents:0,head:p.head,reason:'No PR found yet; a prior write cannot be assumed absent'};assert(await remoteHead()===p.base,'Remote base moved; obtain fresh review before publishing');const branch=branchFor(q),ref='refs/heads/'+branch;const remote=(await git(['ls-remote','--heads',g.remoteUrl,ref])).split(/\s+/)[0];assert(!remote||remote===p.head,'Controlled branch points to another head');if(!remote){notCancelled();save({...state,effectPossible:true,step:'branch_push'});await git(['push','--porcelain','--force-with-lease='+ref+':',g.remoteUrl,p.head+':'+ref])}assert(await remoteHead()===p.base,'Remote base moved after branch publication; no PR is created');notCancelled();save({...state,effectPossible:true,step:'pr_create'});const pr=verifyPR(await api(root+'/pulls',{method:'POST',body:{title:'Oxagen batch '+q.batchId,head:branch,base:g.defaultBranch,body:`Reviewed batch ${q.batchId}.\n\nReviewed head: ${p.head}\nReviewed base: ${p.base}\nReview session: ${p.review.sessionId}\n\n${marker(q)}`}}),p,branch);return receipt(q,{pr:prRef(pr)})}
 if(q.kind==='ci'){const pr=await loadPR(q);assert(!pr.merged&&pr.state==='open','PR is not open for pre-merge CI');assert(await remoteHead()===p.base,'Remote base changed; fresh review required');const result=await waitChecks(p.head,g.requiredChecks,reconcileOnly,q.timeoutSeconds);return result.requiredChecksPassed?receipt(q,{...result,pr:prRef(pr)}):ciFailure(q,result,'Required exact-head CI is not successful')}
 if(q.kind==='merge'){let pr=await loadPR(q);if(pr.merged){save({...state,effectPossible:true,step:'merged_effect_observed'});assert(state.mergeProtection?.verified===true,'Merged effect lacks its recorded pre-write protection proof; operator review required');return receipt(q,{...await mergeProof(q,pr,tree),mergeProtection:state.mergeProtection,reconciled:true})}if(reconcileOnly)return {status:'unknown',operationId:q.id,opId:q.id,costCents:0,head:p.head,reason:'Merge not confirmed; do not repeat an uncertain merge write'};assert(pr.state==='open'&&!pr.draft,'Open ready PR required');assert(await remoteHead()===p.base&&pr.base.sha===p.base,'Remote base moved; fresh review required');const ci=await checks(p.head,g.requiredChecks);assert(ci.requiredChecksPassed,'Required CI changed before merge');assert(await remoteHead()===p.base,'Base changed immediately before merge');const protection=await mergeProtection();assert(await remoteHead()===p.base,'Base changed after server protection check');notCancelled();save({...state,effectPossible:true,step:'merge',mergeProtection:protection});const merged=await api(root+'/pulls/'+pr.number+'/merge',{method:'PUT',body:{sha:p.head,merge_method:g.mergeMethod}});assert(merged.merged===true&&SHA.test(merged.sha),'GitHub did not confirm synchronous merge');pr=await loadPR(q);assert(pr.merge_commit_sha===merged.sha,'Merge response and PR disagree');return receipt(q,{...await mergeProof(q,pr,tree),mergeProtection:protection})}
 if(q.kind==='post_merge_ci'){const prior=p.previousReceipts?.merge;assert(prior?.merged&&prior.reviewedHead===p.head&&prior.reviewedBase===p.base&&SHA.test(prior.mergedHead),'Verified prior merge receipt required');const pr=await loadPR(q),proof=await mergeProof(q,pr,tree);assert(proof.mergedHead===prior.mergedHead&&proof.mergedTree===prior.mergedTree,'Actual merged commit changed');const result=await waitChecks(proof.mergedHead,g.postMergeRequiredChecks,reconcileOnly,q.timeoutSeconds);return result.requiredChecksPassed?receipt(q,{...proof,...result,postMerge:true}):ciFailure(q,result,'Required actual-commit CI is not successful')}throw new Error('Unsupported operation')}
 async function execute(request){const q=request.kind==='reconcile'?request.operation:request;reviewed(q);fs.mkdirSync(g.stateDir,{recursive:true,mode:0o700});const file=path.join(g.stateDir,digest(q.id)+'.json'),lock=file+'.lock',requestDigest=digest({id:q.id,kind:q.kind,batchId:q.batchId,payload:q.payload,gitPolicy:{repository:g.repository,repositoryId:g.repositoryId,hostname:g.hostname,defaultBranch:g.defaultBranch,mergeMethod:g.mergeMethod,requiredChecks:g.requiredChecks,postMergeRequiredChecks:g.postMergeRequiredChecks}});acquireLock(lock,request.kind==='reconcile');let state=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{requestDigest,effectPossible:false};const save=next=>{state={...next,requestDigest};durable(file,state)};try{assert(state.requestDigest===requestDigest,'Operation ID reused for changed request');if(state.result?.status==='succeeded')return state.result;const reconcileOnly=request.kind==='reconcile'||state.effectPossible;const result=await perform(q,state,save,reconcileOnly);save({...state,result});return result}catch(e){if(e.stderrTail){try{fs.writeFileSync(path.join(g.stateDir,digest(q.id)+'.stderr.log'),e.stderrTail,{mode:0o600})}catch{}}const result={status:state.effectPossible||e.childStopUnproved?'unknown':'failed',operationId:q.id,opId:q.id,costCents:0,head:q.payload.head,reason:e.message+(e.stderrTail?' (stderr kept in github-operations/'+digest(q.id)+'.stderr.log)':''),noExternalEffect:!state.effectPossible,allChildrenStopped:!e.childStopUnproved};if(state.requestDigest===requestDigest)save({...state,result});return result}finally{fs.rmSync(lock,{recursive:true})}}
 return {preflight,initializeRepository,execute};
}
export const preflight=config=>createAdapter(config).preflight();
export const initializeRepository=config=>createAdapter(config).initializeRepository();
export const execute=(request,config)=>createAdapter(config).execute(request);
