import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {canonical,digest,Journal,invokeStage,verifyCertificate,validatePlan,agentCommand,validateReview,processJSON,fileSnapshot,requestRetry,invokeRollbackStage,reconcileNoEffect} from '../lib/core.mjs';
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'oxagen-runner-test-'));
const plan=JSON.parse(fs.readFileSync(new URL('../examples/plan.json',import.meta.url)));
test('plan has ordered bounded batches and independent opposite reviewers',()=>{validatePlan(plan);assert.equal(plan.batches.length,22);const bad=structuredClone(plan);bad.batches[0].depends=['missing'];assert.throws(()=>validatePlan(bad));});
test('real CLI argv uses supported flags and no shell interpolation',()=>{const c=agentCommand('codex','review','/tmp/a;touch nope','model',100);assert.equal(c.cwd,'/tmp/a;touch nope');assert(c.args.includes('read-only'));assert(!c.args.includes('--max-budget-usd'));const a=agentCommand('claude','implement','/tmp/x',null,250);assert(a.args.includes('2.50'));assert(a.args.includes('--bare'));});
test('phase-zero certificate binds every exact hash and plan',()=>{const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const payload={scope:'phase-zero',planDigest:digest(plan),files:{'desktop.html':'abc'},expiresAt:new Date(Date.now()+60000).toISOString()};const cert={payload,signature:crypto.sign(null,Buffer.from(canonical(payload)),privateKey).toString('base64')};assert(verifyCertificate(cert,publicKey,payload));assert.throws(()=>verifyCertificate(cert,publicKey,{...payload,files:{'desktop.html':'changed'}}));});
test('snapshot rejects files escaping through a symlink',()=>{const dir=temp();fs.symlinkSync('/etc/passwd',path.join(dir,'escape'));assert.throws(()=>fileSnapshot(dir,['escape']));fs.rmSync(dir,{recursive:true});});
test('review must be fresh exact head and opposite harness',()=>{const r={head:'h',harness:'claude',verdict:'pass',findings:[],sessionId:'new'};validateReview(r,{head:'h',implementationHarness:'codex',reviewerHarness:'claude'});assert.throws(()=>validateReview(r,{head:'changed',implementationHarness:'codex',reviewerHarness:'claude'}));assert.throws(()=>validateReview(r,{head:'h',implementationHarness:'claude',reviewerHarness:'claude'}));});
test('journal reloads durable state and rejects tampering',()=>{const dir=temp();const j=new Journal(dir,'plan');j.record('test',{...j.state,answer:42});assert.equal(new Journal(dir,'plan').state.answer,42);fs.appendFileSync(j.file,'broken\n');assert.throws(()=>new Journal(dir,'plan'));fs.rmSync(dir,{recursive:true});});
test('unknown fake adapter result stays blocked and never repeats automatically',async()=>{const dir=temp();const j=new Journal(dir,'plan');let calls=0;const op={id:'one',kind:'merge'};await assert.rejects(invokeStage(j,op,async()=>{calls++;throw Error('connection lost')}));assert.equal(new Journal(dir,'plan').state.active.id,'one');await assert.rejects(invokeStage(j,op,async()=>{calls++;return {operationId:'one',status:'succeeded'}}));assert.equal(calls,1);fs.rmSync(dir,{recursive:true});});
test('successful fake adapter receipt still awaits durable stage adoption',async()=>{const dir=temp();const j=new Journal(dir,'plan');const r=await invokeStage(j,{id:'one',kind:'agent'},async()=>({operationId:'one',status:'succeeded',costCents:0}));assert.equal(r.operationId,'one');assert.equal(j.state.active.id,'one');fs.rmSync(dir,{recursive:true});});
test('trusted subprocess input is JSON over stdin, not shell code',async()=>{const dir=temp();const file=path.join(dir,'fake.mjs');fs.writeFileSync(file,"let s='';for await(const c of process.stdin)s+=c;process.stdout.write(JSON.stringify({echo:JSON.parse(s)}));");const r=await processJSON(process.execPath,[file],{text:'$(touch /tmp/never-run)'},{timeoutSeconds:2});assert.equal(r.echo.text,'$(touch /tmp/never-run)');fs.rmSync(dir,{recursive:true});});
test('hung fake adapter is time bounded',async()=>{const dir=temp();const file=path.join(dir,'hang.mjs');fs.writeFileSync(file,'setInterval(()=>{},1000)');await assert.rejects(processJSON(process.execPath,[file],{},{timeoutSeconds:0.05}),/timeout/);fs.rmSync(dir,{recursive:true});});

test('product paths and required certification entries cannot escape phase-zero contract',()=>{const bad=structuredClone(plan);bad.batches.find(x=>x.phase==='product').allowedPaths.push('phase0/');assert.throws(()=>validatePlan(bad),/cannot edit phase-zero/);const outside=structuredClone(plan);outside.certificationFiles[0]='README.md';assert.throws(()=>validatePlan(outside),/inside phase0/)});

test('retry is restricted to the exact blocked review batch',()=>{const dir=temp();try{const j=new Journal(dir,'plan');const first=plan.batches[0].id,second=plan.batches[1].id;j.record('seed',{...j.state,batches:{[first]:{stage:'done',attempt:1},[second]:{stage:'review',attempt:1}},blocked:{batchId:second,knownNoExternalEffect:true}});assert.throws(()=>requestRetry(j,plan,first),/exact blocked review/);assert.equal(j.state.blocked.batchId,second);requestRetry(j,plan,second);assert.equal(j.state.batches[second].stage,'retry');assert.equal(j.state.blocked,null)}finally{fs.rmSync(dir,{recursive:true,force:true})}});

test('rollback records active recovery atomically and no-effect reconcile restores failed health',async()=>{const dir=temp();try{const j=new Journal(dir,'plan'),blocked={batchId:'release',rollbackRequired:true,reason:'Failed health'},pendingReceipt={kind:'staging_health',result:{healthy:false}};j.record('seed',{...j.state,blocked,pendingReceipt});await assert.rejects(invokeRollbackStage(j,{id:'rollback-one',kind:'rollback',batchId:'release'},async()=>{const disk=new Journal(dir,'plan');assert.equal(disk.state.active.id,'rollback-one');assert.deepEqual(disk.state.active.recovery,{blocked,pendingReceipt});throw Error('Lost response')}),/Lost response/);const events=fs.readFileSync(j.file,'utf8').trim().split('\n').map(JSON.parse);assert(events.every(e=>e.state.blocked||e.state.active));const restored=new Journal(dir,'plan');reconcileNoEffect(restored,{operationId:'rollback-one',status:'succeeded',noExternalEffect:true,allChildrenStopped:true,costCents:0});assert.deepEqual(restored.state.blocked,blocked);assert.deepEqual(restored.state.pendingReceipt,pendingReceipt);assert.equal(restored.state.active,null);await assert.rejects(invokeStage(restored,{id:'forbidden',kind:'production_deploy'},async()=>({})),/blocked/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
