import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import {Engine} from '../lib/engine.mjs';import {Journal,digest,canonical,fileSnapshot,hashFile} from '../lib/core.mjs';
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'oxagen-engine-'));const control=path.join(dir,'control');fs.mkdirSync(control);const plan={version:1,certificationFiles:['phase0/desktop.html','phase0/web.html','phase0/openapi.json'],batches:[{id:'design',phase:'design',depends:[],implementer:'codex',allowedPaths:['phase0/'],maxCostCents:100,timeoutSeconds:5,maxAttempts:2,goal:'Make three design artifacts.',acceptance:['All design flows are covered.','All examples pass required checks.']},{id:'product',phase:'product',depends:['design'],implementer:'claude',allowedPaths:['apps/'],maxCostCents:100,timeoutSeconds:5,maxAttempts:2,goal:'Build the certified example.',acceptance:['Honor all certified contracts.','Pass isolation and recovery checks.']}]};const {privateKey,publicKey}=crypto.generateKeyPairSync('ed25519');const source=path.join(control,'Design.md');fs.writeFileSync(source,'Approved design input');const inputManifest=path.join(control,'source-inputs.json');fs.writeFileSync(inputManifest,JSON.stringify({version:1,files:[{path:'Design.md',source,sha256:hashFile(source)}]}));const config={version:1,inputManifest,inputRoot:path.join(dir,'inputs'),controlDir:control,workRoot:path.join(dir,'work'),runBudgetCents:1000,maxRunSeconds:120,targets:{repository:'test-repo',staging:'test-stage',production:'test-prod'},phaseZeroCertificate:path.join(control,'cert.json'),certifierPublicKey:path.join(control,'public.pem')};fs.writeFileSync(config.certifierPublicKey,publicKey.export({type:'spki',format:'pem'}));return {dir,plan,config,privateKey}}
function adapter(f,{certify=true,stale=false}={}){let session=0;return async q=>{if(q.kind==='preflight')return {status:'succeeded',controlProtected:true,gitMetadataProtected:true,agentEgressControlled:true,credentialsOutsideAgents:true,hardBudgetEnforced:true,scannerEnforced:true,reviewIsolation:true,hookTargetsPinned:true,inputsReadOnly:true,modelsSupported:true};const p=q.payload,r={status:'succeeded',operationId:q.id,costCents:0,head:p.head};if(q.kind==='agent'){r.budgetReceipt='fake-budget';r.isolationReceipt='fake-isolation';r.allChildrenStopped=true;if(p.role==='implement'){if(q.batchId==='design'){fs.mkdirSync(path.join(p.worktree,'phase0'));for(const file of f.plan.certificationFiles)fs.writeFileSync(path.join(p.worktree,file),'design-only')}else{fs.mkdirSync(path.join(p.worktree,'apps'));fs.writeFileSync(path.join(p.worktree,'apps','hello.txt'),'product')}}else r.review={head:stale?'stale':p.head,harness:p.harness,sessionId:'fresh-'+(++session),verdict:'pass',findings:[]}}
if(q.kind==='pull_request')r.pr={number:session,url:'https://example.invalid/test-pr'};if(q.kind==='ci')Object.assign(r,{requiredChecksPassed:true,checkedHead:p.head});if(q.kind==='merge'){Object.assign(r,{merged:true,mergedHead:p.head,baseMatched:true});if(q.batchId==='design'&&certify){const payload={scope:'phase-zero',planDigest:digest(f.plan),inputsDigest:digest({'Design.md':hashFile(path.join(f.config.controlDir,'Design.md'))}),files:fileSnapshot(p.worktree,f.plan.certificationFiles),expiresAt:new Date(Date.now()+60000).toISOString()};fs.writeFileSync(f.config.phaseZeroCertificate,JSON.stringify({payload,signature:crypto.sign(null,Buffer.from(canonical(payload)),f.privateKey).toString('base64')}))}}return r;}}
test('fake end-to-end design, certification, opposite review, PR, CI and exact merge',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));await new Engine({...f,journal:j,hook:adapter(f)}).run();assert.equal(j.state.batches.product.stage,'done');assert.equal(j.state.batches.design.review.harness,'claude');assert.equal(j.state.batches.product.review.harness,'codex');assert(j.state.certificateDigest);assert.notEqual(j.state.batches.product.worktree,j.state.batches.product.reviewWorktree);assert.notEqual(j.state.batches.design.worktree,j.state.batches.design.reviewWorktree)}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('no product agent starts before phase-zero certificate exists',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));await assert.rejects(new Engine({...f,journal:j,hook:adapter(f,{certify:false})}).run());assert.equal(j.state.batches.product.stage,'implement');assert(!fs.existsSync(path.join(j.state.batches.product.worktree,'apps')))}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('stale opposite-harness review blocks PR and merge',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));await assert.rejects(new Engine({...f,journal:j,hook:adapter(f,{stale:true})}).run(),/stale/);assert.equal(j.state.blocked.knownNoExternalEffect,true);assert.equal(j.state.batches.design.pr,undefined)}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('saved known receipt survives restart without repeating a remote stage',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));j.record('seed',{...j.state,startedAt:Date.now(),spentCents:0,batches:{design:{stage:'quality',spentCents:0}}});let calls=0;const hook=async op=>{calls++;return {operationId:op.id,status:'succeeded',costCents:0,head:'exact'}};const b=f.plan.batches[0];await new Engine({...f,journal:j,hook}).external('quality',b,{head:'exact'});const restored=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));await new Engine({...f,journal:restored,hook}).external('quality',b,{head:'exact'});assert.equal(calls,1);await assert.rejects(new Engine({...f,journal:restored,hook}).external('quality',b,{head:'changed'}),/original transition/)}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('a changed deployment artifact blocks production before any deploy call',async()=>{const f=fixture();f.plan.batches[1].phase='release';try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);let production=false;const hook=async op=>{if(op.kind.startsWith('production'))production=true;const r=await base(op);if(op.kind==='release_preflight')Object.assign(r,{artifactDigest:'qualified',backupVerified:true,migrationsRehearsed:true,rollbackReady:true});if(op.kind==='staging_deploy')Object.assign(r,{artifactDigest:'changed',target:f.config.targets.staging});return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/artifact changed/);assert.equal(production,false)}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});

test('a product edit to certified phase-zero files is stopped before review or remote gates',async()=>{const f=fixture();f.plan.batches[1].allowedPaths.push('phase0/');try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);const calls=[];const hook=async op=>{calls.push([op.batchId,op.kind,op.payload?.role]);const r=await base(op);if(op.batchId==='product'&&op.kind==='agent'&&op.payload.role==='implement')fs.writeFileSync(path.join(op.payload.worktree,'phase0/openapi.json'),'changed');return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/exact inputs/);assert.deepEqual(calls.filter(x=>x[0]==='product'),[['product','agent','implement']]);assert.equal(j.state.batches.product.stage,'implement')}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});

test('leading-space file names do not bypass allowed path checks',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);const hook=async op=>{const r=await base(op);if(op.batchId==='product'&&op.kind==='agent'&&op.payload.role==='implement'){fs.mkdirSync(path.join(op.payload.worktree,' apps'));fs.writeFileSync(path.join(op.payload.worktree,' apps/escape.txt'),'outside')}return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/outside certified batch paths:  apps\/escape.txt/);assert.equal(j.state.batches.product.stage,'implement')}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});

test('certificate expiry during implementation prevents review and merge',async()=>{const f=fixture(),now=Date.now;let advance=0;Date.now=()=>now()+advance;try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);let productCalls=0;const hook=async op=>{const r=await base(op);if(op.batchId==='product'){productCalls++;if(op.kind==='agent'&&op.payload.role==='implement')advance=61000}return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/expired/);assert.equal(productCalls,1);assert.equal(j.state.batches.product.stage,'implement')}finally{Date.now=now;fs.rmSync(f.dir,{recursive:true,force:true})}});

test('a changed valid certificate cannot replace the certificate pinned to a running batch',async()=>{const f=fixture();try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);const hook=async op=>{const r=await base(op);if(op.batchId==='product'&&op.kind==='agent'&&op.payload.role==='implement'){const cert=JSON.parse(fs.readFileSync(f.config.phaseZeroCertificate));cert.payload.expiresAt=new Date(Date.now()+90000).toISOString();cert.signature=crypto.sign(null,Buffer.from(canonical(cert.payload)),f.privateKey).toString('base64');fs.writeFileSync(f.config.phaseZeroCertificate,JSON.stringify(cert))}return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/certificate changed during/);assert.equal(j.state.batches.product.stage,'implement')}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});

test('certificate expiry during a quality gate prevents the next remote action',async()=>{const f=fixture(),now=Date.now;let advance=0;Date.now=()=>now()+advance;try{const j=new Journal(path.join(f.config.controlDir,'state'),digest(f.plan));const base=adapter(f);const calls=[];const hook=async op=>{if(op.batchId==='product')calls.push(op.kind);const r=await base(op);if(op.batchId==='product'&&op.kind==='quality')advance=61000;return r};await assert.rejects(new Engine({...f,journal:j,hook}).run(),/expired/);assert.deepEqual(calls,['agent','agent','quality']);assert.equal(j.state.pendingReceipt.kind,'quality')}finally{Date.now=now;fs.rmSync(f.dir,{recursive:true,force:true})}});

// Regression: the 'preparing' checkpoint must carry the checkout it selected. A retry picks the prior
// failed head, and a crash between that checkpoint and the worktree add used to resume from the branch
// base instead, silently discarding the implementation being retried.
test('a crash after the preparing checkpoint still recreates the retried implementation',async()=>{const f=fixture();try{
 const statePath=path.join(f.config.controlDir,'state');
 const j=new Journal(statePath,digest(f.plan)),b=f.plan.batches[0];
 await new Engine({...f,journal:j,hook:adapter(f)}).preflight();
 const first=new Engine({...f,journal:j,hook:adapter(f)});
 const base=first.head();
 first.prepare(b);
 const r=j.state.batches[b.id];
 fs.mkdirSync(path.join(r.worktree,'phase0'));
 for(const file of f.plan.certificationFiles)fs.writeFileSync(path.join(r.worktree,file),'retried work');
 const retriedHead=first.commit(b,r);
 assert.notEqual(retriedHead,base);
 // core.retry() records the failed attempt exactly this way.
 j.record('batch.retry',{...j.state,batches:{...j.state.batches,[b.id]:{...j.state.batches[b.id],head:retriedHead,stage:'retry'}}});
 // Crash immediately after the 'preparing' checkpoint, before `git worktree add`.
 class Crashing extends Engine{batchSave(id,value,changes){super.batchSave(id,value,changes);if(value.stage==='preparing')throw new Error('simulated controller crash')}}
 assert.throws(()=>new Crashing({...f,journal:j,hook:adapter(f)}).prepare(b),/simulated controller crash/);
 // Resume from the journal on disk, as a restarted controller does.
 const resumed=new Journal(statePath,digest(f.plan));
 assert.equal(resumed.state.batches[b.id].stage,'preparing');
 const engine=new Engine({...f,journal:resumed,hook:adapter(f)});
 engine.prepare(b);
 const after=resumed.state.batches[b.id];
 const head=execFileSync('/usr/bin/git',['-C',after.worktree,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
 assert.equal(head,retriedHead,'resume must recreate the retried implementation, not the branch base');
 assert.equal(fs.readFileSync(path.join(after.worktree,'phase0/openapi.json'),'utf8'),'retried work');
}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
