import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {build,recoverArtifact,validateArtifactConfig,validateDockerfile} from '../adapters/local-artifacts.mjs';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'oxagen-artifact-')),controlDir=path.join(root,'control');fs.mkdirSync(controlDir);const source=path.join(root,'source');fs.mkdirSync(source);const env={PATH:'/usr/bin:/bin',GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_AUTHOR_NAME:'Test',GIT_AUTHOR_EMAIL:'test@localhost',GIT_COMMITTER_NAME:'Test',GIT_COMMITTER_EMAIL:'test@localhost'};const git=args=>execFileSync('/usr/bin/git',args,{env,encoding:'utf8'}).trim();git(['init',source]);const base='public.example/base@sha256:'+'b'.repeat(64);for(const role of ['api','gateway','worker'])fs.writeFileSync(path.join(source,role+'.Dockerfile'),'FROM '+base+'\nCOPY . /app\n');fs.writeFileSync(path.join(source,'product.txt'),'checked source');git(['-C',source,'add','.']);git(['-C',source,'commit','-m','Checked merge']);const head=git(['-C',source,'rev-parse','HEAD']);git(['clone','--bare',source,path.join(controlDir,'product.git')]);
 const aws={command:'/usr/bin/aws',configFile:path.join(controlDir,'aws-config'),credentialsFile:path.join(controlDir,'aws-credentials'),homeDir:path.join(controlDir,'aws-home')};for(const f of [aws.configFile,aws.credentialsFile])fs.writeFileSync(f,'[fixture]\n',{mode:0o600});fs.mkdirSync(aws.homeDir);
 const targets=Object.fromEntries(['staging','production'].map((name,i)=>[name,{accountId:String(i+1).repeat(12),region:'us-west-2',profile:name+'-push',roleArn:`arn:aws:iam::${String(i+1).repeat(12)}:role/Push`,repositories:{api:'oxagen/api',gateway:'oxagen/gateway',worker:'oxagen/worker'}}]));
 const config={adapter:'local',controlDir,runnerDigest:'fixture',local:{deployment:{aws},artifacts:{dockerCommand:'/usr/bin/docker',dockerHost:'unix:///var/run/docker.sock',skopeoCommand:'/usr/bin/skopeo',builderName:'oxagen',builderContainer:'buildx_buildkit_oxagen0',builderImageId:'sha256:'+'c'.repeat(64),buildxConfigDir:path.join(controlDir,'buildx'),builderMemoryBytes:4096,builderCpuQuota:200000,builderCpuPeriod:100000,timeoutSeconds:60,maxImageBytes:1000000,baseImages:[base],dockerfiles:{api:'api.Dockerfile',gateway:'gateway.Dockerfile',worker:'worker.Dockerfile'},targets}}};
 const request={id:'release-one',timeoutSeconds:60,payload:{executionHead:head,previousReceipts:{post_merge_ci:{checkedHead:head,requiredChecksPassed:true}}}};
 const manifest=JSON.stringify({schemaVersion:2,mediaType:'application/vnd.oci.image.manifest.v1+json',config:{digest:'sha256:'+'d'.repeat(64)},layers:[]});const imageDigest='sha256:'+sha(manifest),calls=[];let mismatch=false,failPush=false;
 const run=async(c,args,opts)=>{calls.push({c,args,opts});let value={};if(c.endsWith('docker')){if(args.includes('buildx')&&args.includes('inspect'))return {exitCode:0,stdout:'Name: oxagen\nDriver: docker-container\nNodes:\nName: oxagen0\nEndpoint: unix:///var/run/docker.sock\n',stderr:''};if(args.includes('inspect'))value=[{Image:config.local.artifacts.builderImageId,State:{Running:true},HostConfig:{Memory:4096,CpuQuota:200000,CpuPeriod:100000},Mounts:[],Config:{Env:[]}}];else{const out=args[args.indexOf('--output')+1].split('dest=')[1].split(',')[0];fs.writeFileSync(out,'OCI fixture');assert.equal(fs.readFileSync(path.join(args.at(-1),'product.txt'),'utf8'),'checked source');assert(!fs.existsSync(path.join(args.at(-1),'.git')))}}
 else if(c.endsWith('skopeo')){if(args.includes('--raw'))return {exitCode:0,stdout:manifest,stderr:''};if(args.includes('--config'))value={os:'linux',architecture:'amd64',config:{Labels:{'org.opencontainers.image.revision':head}}};else if(args.includes('copy')){if(failPush)throw Error('Lost push reply');assert(args.includes('--preserve-digests'))}else value={Digest:imageDigest}}
 else if(c.endsWith('aws')){const profile=args[args.indexOf('--profile')+1],t=Object.values(targets).find(x=>x.profile===profile);if(args.includes('get-caller-identity'))value={Account:t.accountId,Arn:`arn:aws:sts::${t.accountId}:assumed-role/Push/test`};if(args.includes('describe-repositories'))value={repositories:Object.values(t.repositories).map(r=>({registryId:t.accountId,repositoryName:r,repositoryUri:`${t.accountId}.dkr.ecr.${t.region}.amazonaws.com/${r}`,imageTagMutability:'IMMUTABLE'}))};if(args.includes('get-login-password'))return {exitCode:0,stdout:'fake-token\n',stderr:''};if(args.includes('describe-images'))value={imageDetails:[{imageDigest:mismatch?'sha256:'+'e'.repeat(64):imageDigest}]}}
 return {exitCode:0,stdout:JSON.stringify(value),stderr:''};};
 return {root,config,request,run,calls,head,imageDigest,setMismatch:()=>mismatch=true,setFailPush:()=>failPush=true};
}
test('artifact profile rejects mutable bases and shared staging/production account',()=>{const f=fixture();try{validateArtifactConfig(f.config);f.config.local.artifacts.targets.production.accountId=f.config.local.artifacts.targets.staging.accountId;assert.throws(()=>validateArtifactConfig(f.config));assert.throws(()=>validateDockerfile('FROM image:latest',[]));assert.throws(()=>validateDockerfile('FROM x\nADD https://example.test/x /x',['x']));assert.throws(()=>validateDockerfile('FROM x\nRUN --mount=type=secret cat /secret',['x']));assert.throws(()=>validateDockerfile('# syntax=third-party\nFROM x',['x']));assert.throws(()=>validateDockerfile('FROM x\nCOPY --from=outside:latest /a /a',['x']));}finally{fs.rmSync(f.root,{recursive:true,force:true})}});
test('one checked merge builds OCI images once and pushes exact digests to distinct targets without build credentials',async()=>{const f=fixture();try{const r=await build(f.request,f.config,{run:f.run});assert.equal(r.executionHead,f.head);assert.equal(Object.keys(r.images).length,3);assert.equal(r.images.api.digest,f.imageDigest);assert(r.images.api.uris.production.startsWith('222222222222.'));assert.equal(f.calls.filter(x=>x.args.includes('build')&&x.args.includes('buildx')).length,3);for(const x of f.calls.filter(x=>x.args.includes('build')&&x.args.includes('buildx'))){assert(x.args.includes('--network=none'));assert(!Object.keys(x.opts.env).some(k=>k.startsWith('AWS_')));assert(!x.args.some(a=>/password|token|secret/i.test(a)))}assert.equal(f.calls.filter(x=>x.args.includes('copy')).length,6);const count=f.calls.length;assert.deepEqual(await build(f.request,f.config,{run:f.run}),r);assert.equal(f.calls.length,count);assert.deepEqual(await recoverArtifact(f.request,f.config),r);assert(!fs.readdirSync(path.join(f.config.controlDir,'release-artifacts',f.request.id)).some(n=>n.startsWith('auth-')))}finally{fs.rmSync(f.root,{recursive:true,force:true})}});
test('stale CI and changed artifact operation bindings stop before building',async()=>{const f=fixture();try{f.request.payload.previousReceipts.post_merge_ci.checkedHead='0'.repeat(40);await assert.rejects(build(f.request,f.config,{run:f.run}),/actual merge/);assert.equal(f.calls.length,0);f.request.payload.previousReceipts.post_merge_ci.checkedHead=f.head;await build(f.request,f.config,{run:f.run});f.config.local.artifacts.maxImageBytes++;await assert.rejects(build(f.request,f.config,{run:f.run}),/changed/)}finally{fs.rmSync(f.root,{recursive:true,force:true})}});
test('ECR digest mismatch blocks release and cannot be silently rebuilt',async()=>{const f=fixture();try{f.setMismatch();await assert.rejects(build(f.request,f.config,{run:f.run}),/digest differs/);const count=f.calls.length;await assert.rejects(build(f.request,f.config,{run:f.run}),/unfinished/);assert.equal(f.calls.length,count);await assert.rejects(recoverArtifact(f.request,f.config,{run:f.run}),/incomplete|mismatched/)}finally{fs.rmSync(f.root,{recursive:true,force:true})}});
test('lost push replies keep a durable exact digest intent and remove transient registry token',async()=>{const f=fixture();try{f.setFailPush();await assert.rejects(build(f.request,f.config,{run:f.run}),/Lost push/);const dir=path.join(f.config.controlDir,'release-artifacts',f.request.id),m=JSON.parse(fs.readFileSync(path.join(dir,'operation.json')));assert.equal(m.inFlight.kind,'push');assert.equal(m.inFlight.digest,f.imageDigest);assert(!fs.existsSync(path.join(dir,'auth-staging.json')));const count=f.calls.length;const recovered=await recoverArtifact(f.request,f.config,{run:f.run});assert.equal(recovered.images.api.digest,f.imageDigest);assert(f.calls.slice(count).every(x=>x.c.endsWith('aws')&&!x.args.includes('get-login-password')))}finally{fs.rmSync(f.root,{recursive:true,force:true})}});
