import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';
import {PRICE_PROFILES,PRICE_DIGEST,validatePricing,scanValue,normalizeRequest,usageCost,parseUsage,BudgetLedger,createBroker} from '../adapters/local-execution-broker.mjs';
import {dockerArgs} from '../adapters/local-execution-docker.mjs';import {parseResult,buildInvocation,preflight} from '../adapters/local-execution.mjs';
const approval=()=>({profileDigest:PRICE_DIGEST,expiresAt:new Date(Date.now()+86400000).toISOString()});
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'ox-local-'));
const policy={version:'one',rules:[{match:'PRIVATE',action:'redact'}]};
function post(socket,body,url='/v1/responses'){return new Promise((resolve,reject)=>{const q=http.request({socketPath:socket,path:url,method:'POST',headers:{'content-type':'application/json'}},r=>{let text='';r.on('data',c=>text+=c);r.on('end',()=>resolve({status:r.statusCode,text}))});q.on('error',reject);q.end(JSON.stringify(body))})}
test('local pricing approval binds the exact reviewed rates and has a short expiry',()=>{validatePricing(approval());assert.throws(()=>validatePricing({...approval(),profileDigest:'wrong'}));assert.throws(()=>validatePricing({...approval(),expiresAt:'2020-01-01'}))});
test('full-context reservation bounds input without trusting token estimates',()=>{const r=normalizeRequest({model:'gpt-5.3-codex',input:'x',max_output_tokens:99999},'gpt-5.3-codex',8192);assert.equal(r.body.max_output_tokens,8192);assert.equal(r.reservationNano,400000*1750+8192*14000);const a=normalizeRequest({model:'claude-sonnet-4-6',messages:[]},'claude-sonnet-4-6',8192);assert.equal(a.reservationNano,1000000*6000+8192*15000)});
test('unbounded remote state, hosted tools, premium tiers and media are rejected',()=>{const b={model:'gpt-5.3-codex',input:'x'};for(const fields of [{previous_response_id:'id'},{background:true},{input:[{id:'msg_existing'}]},{input:[{type:null,id:'msg_existing'}]},{input:[{type:'message',role:'user',content:'x',additional_tools:[{type:'code_interpreter'}]}]},{input:[{type:'input_file',file_id:'file-hidden'}]},{input:[{type:'input_file',file_url:'https://elsewhere/file'}]},{input:[{type:'item_reference',id:'item-remote'}]},{service_tier:'priority'},{tools:[{type:'web_search'}]},{input:[{type:'input_image',image_url:'https://elsewhere/'}]}])assert.throws(()=>normalizeRequest({...b,...fields},b.model,20));assert.throws(()=>normalizeRequest({...b,model:'arbitrary'},'arbitrary',20))});
test('full request scan covers nested history, tools, keys and attachments before egress',()=>{const cleaned=scanValue({messages:[{content:'PRIVATE'}],tools:[{input_schema:{PRIVATE:'PRIVATE'}}]},policy);assert.equal(cleaned.messages[0].content,'[REDACTED]');assert.equal(cleaned.tools[0].input_schema['[REDACTED]'],'[REDACTED]');assert.throws(()=>scanValue({history:'SECRET'},{version:'two',rules:[{match:'SECRET',action:'block'}]}))});
test('concurrent reservations cannot spend the same balance and unknown liability stays held',()=>{const dir=temp();try{const l=new BudgetLedger(path.join(dir,'ledger'),100,'q');const id=l.reserve(700000000,'hash');assert.throws(()=>l.reserve(400000000,'another'),/exhausted/);l.unknown(id);assert.throws(()=>l.reserve(1,'retry'),/unknown/);assert.throws(()=>l.receipt(),/liability/);assert(fs.readFileSync(l.file,'utf8').includes('heldNano'));assert.throws(()=>new BudgetLedger(l.file,100,'q'),/already exists/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('terminal provider usage settles conservatively and malformed streams stay unknown',()=>{const p=PRICE_PROFILES['claude-sonnet-4-6'];assert.equal(usageCost(p,{input_tokens:1,output_tokens:2,cache_creation_input_tokens:3,cache_read_input_tokens:4}),3000+30000+18000+1200);const s='data: '+JSON.stringify({type:'message_start',message:{usage:{input_tokens:4,output_tokens:0}}})+'\n\ndata: '+JSON.stringify({type:'message_delta',usage:{output_tokens:2}})+'\n\ndata: {"type":"message_stop"}\n\n';assert.deepEqual(parseUsage(p,s,true),{input_tokens:4,output_tokens:2});assert.throws(()=>parseUsage(p,s.replace('data: {"type":"message_stop"}',''),true));assert.throws(()=>usageCost(p,{input_tokens:2,output_tokens:3,server_tool_use:{web_search_requests:1}}))});
test('real Unix broker sends only scanned body to a fake provider and rejects unknown paths',async()=>{const dir=temp();let broker;try{const socket=path.join(dir,'model.sock'),ledger=new BudgetLedger(path.join(dir,'ledger'),1000,'q');let calls=0;broker=await createBroker({socketPath:socket,model:'gpt-5.3-codex',maxOutputTokens:10,credential:'host-only-fake',ledger,scanPolicy:policy,pricingApproval:approval(),transport:async(p,b,key,o)=>{calls++;assert.equal(key,'host-only-fake');assert.equal(b.input,'[REDACTED]');const text=JSON.stringify({status:'completed',usage:{input_tokens:2,output_tokens:1}});o.onChunk(Buffer.from(text),200,'application/json');return {text,usage:{input_tokens:2,output_tokens:1}}}});assert.equal((await post(socket,{model:'gpt-5.3-codex',input:'PRIVATE'})).status,200);assert.equal((await post(socket,{model:'gpt-5.3-codex',input:'PRIVATE'},'/v1/files')).status,403);assert.equal(calls,1);assert.equal(broker.receipt().costCents,1);assert(!fs.readFileSync(ledger.file,'utf8').includes('PRIVATE'))}finally{if(broker)await broker.close();fs.rmSync(dir,{recursive:true,force:true})}});
test('provider connection loss prevents a new paid attempt through the Unix broker',async()=>{const dir=temp();let broker;try{const socket=path.join(dir,'model.sock'),ledger=new BudgetLedger(path.join(dir,'ledger'),1000,'q');let calls=0;broker=await createBroker({socketPath:socket,model:'gpt-5.3-codex',maxOutputTokens:10,credential:'fake',ledger,scanPolicy:policy,pricingApproval:approval(),transport:async()=>{calls++;throw Error('Lost response')}});assert.equal((await post(socket,{model:'gpt-5.3-codex',input:'x'})).status,502);assert.equal((await post(socket,{model:'gpt-5.3-codex',input:'x'})).status,403);assert.equal(calls,1);assert.throws(()=>broker.receipt())}finally{if(broker)await broker.close();fs.rmSync(dir,{recursive:true,force:true})}});
test('Docker argv fixes isolation, identity, resources, deadline and read-only input mount',()=>{const dir=temp();try{const args=dockerArgs({image:'sha256:'+'a'.repeat(64),name:'probe',uid:1000,gid:1000,timeoutSeconds:30,command:'/usr/local/bin/node',args:['--version'],mounts:[{source:dir,target:'/inputs',readOnly:true}]});for(const expected of ['--network=none','--log-driver=none','--pull=never','--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--pids-limit','--memory','--cpus','/usr/bin/timeout'])assert(args.includes(expected));assert(args.some(x=>x.includes('target=/inputs,readonly')));assert.throws(()=>dockerArgs({image:'latest',uid:0,gid:0,timeoutSeconds:30,name:'bad'}))}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('CLI structured result needs terminal success and exact review head',()=>{const q={payload:{harness:'claude',role:'review',head:'exact'}};const stdout=JSON.stringify({type:'result',subtype:'success',is_error:false,structured_output:{head:'exact',verdict:'pass',findings:[]}});assert.deepEqual(parseResult(stdout,q,'fresh').review,{head:'exact',verdict:'pass',findings:[],harness:'claude',sessionId:'fresh'});assert.throws(()=>parseResult(stdout.replace('exact','stale'),q,'fresh'));assert.throws(()=>parseResult('{"type":"turn.started"}',{payload:{harness:'codex',role:'implement'}},'fresh'))});
const hostConfig=dir=>({controlDir:dir,workRoot:dir+'-work',inputRoot:dir+'-inputs',models:{implement:{codex:'gpt-5.3-codex',claude:'claude-sonnet-4-6'},review:{codex:'gpt-5.3-codex',claude:'claude-sonnet-4-6'}},local:{execution:{uid:1000,gid:1000,cli:{codex:{path:'/usr/local/bin/codex',version:'pinned'},claude:{path:'/usr/local/bin/claude',version:'pinned'}},pricingApproval:approval(),scanPolicy:policy}}});
test('unsupported host fails preflight before a harness or paid call',{skip:process.platform==='linux'?'preflight on Linux needs Docker; covered by the Linux preflight':false},async()=>{const dir=temp();try{await assert.rejects(preflight(hostConfig(dir)),/Linux Docker/)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
test('invocation never carries caller argv, controller paths, or a real provider token',()=>{const dir=temp();try{const config=hostConfig(dir);const q={maxCostCents:100,payload:{harness:'claude',role:'implement',worktree:config.workRoot,prompt:'Read '+config.inputRoot,inputMount:{path:config.inputRoot},command:{args:['untrusted']}}};const invocation=buildInvocation(q,config);assert(!invocation.args.includes('untrusted'));assert.equal(invocation.prompt,'Read /inputs');assert.equal(invocation.env.ANTHROPIC_AUTH_TOKEN,'local-operation-socket')}finally{fs.rmSync(dir,{recursive:true,force:true})}});

test('synthetic provider fixtures require an actual tool-result roundtrip',async()=>{const {fixtureTransport}=await import('../adapters/local-execution-fixture.mjs');for(const model of ['gpt-5.3-codex','claude-sonnet-4-6']){const profile=PRICE_PROFILES[model],anthropic=profile.provider==='anthropic',transport=fixtureTransport('{"verdict":"pass"}');const tools=anthropic?[{name:'Bash',input_schema:{}}]:[{type:'function',name:'exec_command',parameters:{}}];const first=await transport(profile,{model,tools,stream:true},'fake');assert(first.text.includes(anthropic?'tool_use':'function_call'));await assert.rejects(transport(profile,{model,tools,stream:true},'fake'),/tool result/);const fresh=fixtureTransport('done');await fresh(profile,{model,tools,stream:true},'fake');const input=anthropic?{messages:[{role:'user',content:[{type:'tool_result',tool_use_id:'toolu_oxagen_fixture',content:'OXAGEN_LOCAL_TOOL_PROBE'}]}]}:{input:[{type:'function_call_output',call_id:'call_oxagen_fixture',output:'OXAGEN_LOCAL_TOOL_PROBE'}]};const final=await fresh(profile,{model,tools,stream:true,...input},'fake');assert(final.text.includes('done'));assert.deepEqual(fresh.proof(),{requests:2,toolResultSeen:true})}});
test('Docker endpoint profile rejects remote daemons and never inherits saved context',async()=>{const {dockerHostArgs}=await import('../adapters/local-execution-docker.mjs');assert.deepEqual(dockerHostArgs(),['--host','unix:///var/run/docker.sock']);assert.throws(()=>dockerHostArgs('ssh://remote'));assert.throws(()=>dockerHostArgs('tcp://host:2375'))});

test('pricing expiry during an operation blocks new sends before reservation',async()=>{const dir=temp(),now=Date.now;let broker,advanced=0;Date.now=()=>now()+advanced;try{const socket=path.join(dir,'model.sock'),ledger=new BudgetLedger(path.join(dir,'ledger'),1000,'q');let calls=0;broker=await createBroker({socketPath:socket,model:'gpt-5.3-codex',maxOutputTokens:10,credential:'fake',ledger,scanPolicy:policy,pricingApproval:{profileDigest:PRICE_DIGEST,expiresAt:new Date(now()+5000).toISOString()},transport:async()=>{calls++;return {text:'{}',usage:{input_tokens:0,output_tokens:0}}}});advanced=6000;assert.equal((await post(socket,{model:'gpt-5.3-codex',input:'x'})).status,403);assert.equal(calls,0);assert.equal(ledger.pending.size,0)}finally{Date.now=now;if(broker)await broker.close();fs.rmSync(dir,{recursive:true,force:true})}});

test('completed receipt adoption rejects changed controller requests or execution profiles',async()=>{const {verifyRecoveryBinding}=await import('../adapters/local-execution.mjs');const {digest}=await import('../lib/core.mjs');const operation={id:'op',kind:'agent',batchId:'one',maxCostCents:100,payload:{head:'exact'}},config={controlDir:'/control',workRoot:'/work',inputRoot:'/inputs',models:{},local:{execution:{image:'pinned'}}};const meta={controllerDigest:digest(operation),executionConfigDigest:digest({execution:config.local.execution,models:config.models,runnerDigest:config.runnerDigest,maxRunSeconds:config.maxRunSeconds,controlDir:config.controlDir,workRoot:config.workRoot,inputRoot:config.inputRoot})};verifyRecoveryBinding(meta,operation,config);assert.throws(()=>verifyRecoveryBinding(meta,{...operation,payload:{head:'different'}},config));assert.throws(()=>verifyRecoveryBinding(meta,operation,{...config,local:{execution:{image:'changed'}}}))});

test('an input mount can never expose the controller root',()=>{const config={controlDir:'/srv/controller',workRoot:'/srv/agent-work',inputRoot:'/srv/controller/secrets',local:{execution:{}}};assert.throws(()=>buildInvocation({payload:{}},config),/disjoint/);assert.throws(()=>buildInvocation({payload:{}},{...config,inputRoot:'/srv'}),/disjoint/)});

test('a stopped harness with no reservation is a known no-charge failure; any reservation or unknown keeps it uncertain',async()=>{const {ledgerLiability}=await import('../adapters/local-execution.mjs');const dir=temp();try{assert.equal(ledgerLiability(path.join(dir,'missing')),null);const clean=new BudgetLedger(path.join(dir,'clean'),100,'q');assert.deepEqual(ledgerLiability(clean.file),{reservedNano:0,unknown:false});const charged=new BudgetLedger(path.join(dir,'charged'),100,'q');const id=charged.reserve(5,'h');charged.settle(id,5);assert.equal(ledgerLiability(charged.file).reservedNano,5);const lost=new BudgetLedger(path.join(dir,'lost'),100,'q');lost.unknown(lost.reserve(5,'h'));assert.equal(ledgerLiability(lost.file).unknown,true);fs.appendFileSync(clean.file,'{"seq":9,"prev":"bad","type":"settled","hash":"x"}\n');assert.equal(ledgerLiability(clean.file).unknown,true)}finally{fs.rmSync(dir,{recursive:true,force:true})}});
