import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {digest} from '../lib/core.mjs';
import {createAdapter,runCommand} from '../adapters/local-github.mjs';
const BASE='a'.repeat(40),HEAD='b'.repeat(40),MERGED='c'.repeat(40),TREE='d'.repeat(40),OTHER='e'.repeat(40);
function fixture(t,overrides={}){
 const controlDir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'oxagen-gh-')));fs.chmodSync(controlDir,0o700);const auth=path.join(controlDir,'gh');fs.mkdirSync(auth,{mode:0o700});fs.mkdirSync(path.join(controlDir,'product.git'));t.after(()=>fs.rmSync(controlDir,{recursive:true,force:true}));
 const config={controlDir,workRoot:path.join(os.tmpdir(),'isolated-agent'),targets:{repository:'acme/product'},github:{repository:'acme/product',repositoryId:123,hostname:'github.com',defaultBranch:'main',mergeMethod:'squash',gitPath:'/usr/bin/git',ghPath:'/usr/local/bin/gh',authConfigDir:auth,ciWaitSeconds:0,requiredChecks:[{kind:'check_run',name:'tests',appId:42},{kind:'status',name:'security',creatorId:7,appId:8}],postMergeRequiredChecks:[{kind:'check_run',name:'tests',appId:42}],...overrides}};
 const state={tip:BASE,branch:null,pr:null,writes:[],calls:[],failCreateAfter:false,failMergeAfter:false,wrongTree:false,wrongProducer:false,missingChecks:false,failedLatest:false,mergeRace:false,mergeParents:null,repositoryId:123,splitPages:false,wrongStatusCreator:false,newerStatusFailure:false,protectionStrict:true,admin:false,bypass:false,policyCheckApp:42,role:'write'};
 function pr(){return {number:10,html_url:'https://github.com/acme/product/pull/10',state:'open',draft:false,merged:false,merge_commit_sha:null,body:'<!-- oxagen-reviewed-head:'+HEAD+' -->',head:{sha:HEAD,ref:'oxagen/batch-one/'+HEAD,repo:{id:123}},base:{sha:BASE,ref:'main',repo:{id:123}}}}
 const command=async(bin,args,options)=>{state.calls.push({bin,args,options});assert.equal(options.env.GH_TOKEN,undefined);assert.equal(options.env.GITHUB_TOKEN,undefined);assert.equal(options.env.GH_CONFIG_DIR,auth);
  if(bin===config.github.ghPath){if(args[0]==='auth')return '';const endpoint=args.find(x=>x.startsWith('/repos/')||x==='/user');const method=args[args.indexOf('--method')+1],body=options.input?JSON.parse(options.input):null;
   if(endpoint==='/repos/acme/product')return JSON.stringify({id:state.repositoryId,full_name:'acme/product',default_branch:'main',archived:false,disabled:false,permissions:{admin:state.admin,push:true}});
   if(endpoint==='/user')return JSON.stringify({id:321,login:'controller-user',type:'User',site_admin:false});
   if(endpoint.includes('/collaborators/'))return JSON.stringify({user:{id:321},permission:'write',role_name:state.role});
   if(endpoint.endsWith('/protection'))return JSON.stringify({required_status_checks:{strict:state.protectionStrict,checks:[{context:'tests',app_id:state.policyCheckApp},{context:'security',app_id:8}]},enforce_admins:{enabled:true},allow_force_pushes:{enabled:false},allow_deletions:{enabled:false},required_pull_request_reviews:{bypass_pull_request_allowances:{users:state.bypass?[{id:321}]:[],teams:[],apps:[]}}});
   if(endpoint.includes('/git/ref/heads/'))return JSON.stringify({object:{type:'commit',sha:state.tip}});
   if(endpoint.includes('/pulls?'))return JSON.stringify([state.pr?[state.pr]:[]]);
   if(endpoint.endsWith('/pulls')&&method==='POST'){state.writes.push({type:'pr',body});state.pr=pr();if(state.failCreateAfter)throw Error('lost create reply');return JSON.stringify(state.pr)}
   if(endpoint.endsWith('/pulls/10/merge')){state.writes.push({type:'merge',body});assert.equal(body.sha,HEAD);assert.equal(body.merge_method,config.github.mergeMethod);state.pr={...state.pr,merged:true,state:'closed',merge_commit_sha:MERGED};state.tip=MERGED;if(state.mergeRace)state.mergeParents=[OTHER];if(state.failMergeAfter)throw Error('lost merge reply');return JSON.stringify({merged:true,sha:MERGED})}
   if(endpoint.endsWith('/pulls/10'))return JSON.stringify(state.pr);
   if(endpoint.includes('/check-runs?')){const sha=endpoint.split('/commits/')[1].slice(0,40);let runs=state.missingChecks?[]:[{id:11,name:'tests',app:{id:state.wrongProducer?99:42},head_sha:sha,status:'completed',conclusion:'success'}];if(state.failedLatest)runs.push({id:12,name:'tests',app:{id:42},head_sha:sha,status:'completed',conclusion:'failure'});return JSON.stringify(state.splitPages?[{check_runs:runs.slice(0,1)},{check_runs:runs.slice(1)}]:[{check_runs:runs}])}
   if(endpoint.includes('/statuses?')){const old={id:1,context:'security',creator:{id:7},state:'success'};const newer={id:2,context:'security',creator:{id:state.wrongStatusCreator?99:7},state:state.newerStatusFailure?'failure':'success'};return JSON.stringify(state.wrongStatusCreator||state.newerStatusFailure?[[newer],[old]]:[[old]])}
   throw Error('Unrecognized GH command '+endpoint);
  }
  const i=args.indexOf('--git-dir'),a=i<0?args:args.slice(i+2);
  if(a[0]==='check-ref-format'||a.includes('init'))return '';
  if(a[0]==='remote'&&a[1]==='get-url')return 'https://github.com/acme/product.git\n';
  if(a[0]==='fetch')return '';
  if(a[0]==='for-each-ref')return 'refs/heads/main\n';
  if(a[0]==='ls-remote')return state.branch?state.branch+'\trefs/heads/oxagen/batch-one/'+HEAD+'\n':'';
  if(a[0]==='push'){state.writes.push({type:'push',args:a});assert(a.includes('--force-with-lease=refs/heads/oxagen/batch-one/'+HEAD+':'));state.branch=HEAD;return ''}
  if(a[0]==='merge-base')return '';
  if(a[0]==='show')return (state.mergeParents||(config.github.mergeMethod==='squash'?[BASE]:[BASE,HEAD])).join(' ');
  if(a[0]==='rev-parse'){if(a[1]==='--is-bare-repository')return 'true';if(a[1]==='refs/remotes/oxagen/default')return state.tip;if(a[1].endsWith('^{commit}'))return a[1].slice(0,40);if(a[1].endsWith('^{tree}'))return state.wrongTree&&a[1].startsWith(MERGED)?OTHER:TREE;}
  throw Error('Unrecognized git command '+a.join(' '));
 };
 const adapter=createAdapter(config,{command});const request=(kind,id=kind)=>({id,kind,batchId:'batch-one',payload:{head:HEAD,base:BASE,worktree:'/unused',phase:'product',review:{head:HEAD,verdict:'pass',findings:[],sessionId:'independent-review'},targets:{repository:'acme/product'},...(state.pr?{pr:{number:10,url:state.pr.html_url}}:{})}});
 return {config,state,adapter,request,command};
}
test('GitHub preflight pins repository, remote branch, private credentials and checks',async t=>{const f=fixture(t);const r=await f.adapter.preflight();assert.equal(r.repository.head,BASE);assert.equal(r.repository.repository,'acme/product');assert.equal(f.state.writes.length,0);f.state.repositoryId=124;await assert.rejects(f.adapter.preflight(),/Pinned repository/)});
test('PR creation pushes only a new named ref and is idempotent',async t=>{const f=fixture(t),q=f.request('pull_request');const r=await f.adapter.execute(q);assert.equal(r.status,'succeeded');assert.equal(r.operationId,q.id);assert.equal(r.pr.number,10);assert.equal((await f.adapter.execute(q)).pr.number,10);assert.deepEqual(f.state.writes.map(x=>x.type),['push','pr']);assert(f.state.calls.every(c=>!c.args.some(x=>x.includes('GH_TOKEN='))))});
test('lost PR creation reply reconciles existing PR without a second write',async t=>{const f=fixture(t);f.state.failCreateAfter=true;const q=f.request('pull_request');assert.equal((await f.adapter.execute(q)).status,'unknown');assert.equal((await f.adapter.execute({kind:'reconcile',operation:q})).status,'succeeded');assert.equal(f.state.writes.filter(x=>x.type==='pr').length,1)});
test('reconciliation with no observed PR never repeats uncertain creation',async t=>{const f=fixture(t);f.state.failCreateAfter=true;const q=f.request('pull_request');await f.adapter.execute(q);f.state.pr=null;const r=await f.adapter.execute({kind:'reconcile',operation:q});assert.equal(r.status,'unknown');assert.equal(f.state.writes.filter(x=>x.type==='pr').length,1)});
test('CI requires each pinned producer at the exact commit and latest attempt',async t=>{const f=fixture(t);await f.adapter.execute(f.request('pull_request'));for(const flag of ['wrongProducer','missingChecks','failedLatest']){f.state[flag]=true;const r=await f.adapter.execute(f.request('ci',flag));assert.equal(r.status,flag==='failedLatest'?'failed':'unknown');assert.equal(r.requiredChecksPassed,false);f.state[flag]=false}const r=await f.adapter.execute(f.request('ci'));assert.equal(r.requiredChecksPassed,true);assert.equal(r.checkedHead,HEAD)});
for(const method of ['squash','merge'])test(method+' merge proves parent/base/tree and post-merge CI uses actual commit',async t=>{const f=fixture(t,{mergeMethod:method});await f.adapter.execute(f.request('pull_request'));const q=f.request('merge'),r=await f.adapter.execute(q);assert.equal(r.status,'succeeded');assert.equal(r.mergedHead,MERGED);assert.equal(r.reviewedHead,HEAD);assert.equal(r.reviewedBase,BASE);assert.equal(r.baseCompareAndSwap,false);assert.equal(r.provenanceVerified,true);const post=f.request('post_merge_ci');post.payload.previousReceipts={merge:r};const ci=await f.adapter.execute(post);assert.equal(ci.status,'succeeded');assert.equal(ci.checkedHead,MERGED);assert.equal(ci.head,HEAD);assert(f.state.calls.some(c=>c.args.some(x=>x.includes('/commits/'+MERGED+'/check-runs'))))});
test('lost merge reply reconciles proof without repeating merge',async t=>{const f=fixture(t);await f.adapter.execute(f.request('pull_request'));f.state.failMergeAfter=true;const q=f.request('merge');assert.equal((await f.adapter.execute(q)).status,'unknown');assert.equal((await f.adapter.execute({kind:'reconcile',operation:q})).status,'succeeded');assert.equal(f.state.writes.filter(x=>x.type==='merge').length,1)});
test('changed base blocks before merge; race after base read cannot certify merge',async t=>{const f=fixture(t);await f.adapter.execute(f.request('pull_request'));f.state.tip=OTHER;assert.equal((await f.adapter.execute(f.request('merge','pre-race'))).status,'failed');assert(!f.state.writes.some(x=>x.type==='merge'));f.state.tip=BASE;f.state.mergeRace=true;const r=await f.adapter.execute(f.request('merge','post-race'));assert.equal(r.status,'unknown');assert.equal(r.noExternalEffect,false);assert.match(r.reason,/provenance/)});
test('merged tree change blocks adoption and design phase cannot publish',async t=>{const f=fixture(t);const design=f.request('pull_request');design.payload.phase='design';await assert.rejects(f.adapter.execute(design),/Design artifacts/);await f.adapter.execute(f.request('pull_request'));f.state.wrongTree=true;const r=await f.adapter.execute(f.request('merge'));assert.equal(r.status,'unknown');assert.match(r.reason,/tree differs/)});
test('empty check lists and unsupported rebase are rejected before commands',t=>{const f=fixture(t);assert.throws(()=>createAdapter({...f.config,github:{...f.config.github,requiredChecks:[]}}),/At least one/);assert.throws(()=>createAdapter({...f.config,github:{...f.config.github,mergeMethod:'rebase'}}),/Only proved/)});

test('all CI pages are examined and a later status from the wrong identity cannot reuse old green',async t=>{const f=fixture(t);await f.adapter.execute(f.request('pull_request'));f.state.splitPages=true;f.state.failedLatest=true;assert.equal((await f.adapter.execute(f.request('ci','paged-failure'))).requiredChecksPassed,false);f.state.failedLatest=false;f.state.wrongStatusCreator=true;assert.equal((await f.adapter.execute(f.request('ci','wrong-status'))).requiredChecksPassed,false);f.state.wrongStatusCreator=false;f.state.newerStatusFailure=true;assert.equal((await f.adapter.execute(f.request('ci','later-status-failure'))).requiredChecksPassed,false)});
test('cancellation stops reads/publishing and nested local configuration is supported',async t=>{const f=fixture(t);createAdapter({...f.config,github:undefined,local:{github:f.config.github}},{command:async()=>{throw Error('must not call')}});fs.writeFileSync(path.join(f.config.controlDir,'CANCEL'),'stop');const r=await f.adapter.execute(f.request('pull_request'));assert.equal(r.status,'failed');assert.equal(f.state.writes.length,0);assert.equal(f.state.calls.length,0)});
test('operation reuse with a different request fails before any second publication',async t=>{const f=fixture(t);const q=f.request('pull_request');await f.adapter.execute(q);const changed={...q,payload:{...q.payload,review:{...q.payload.review,sessionId:'changed'}}};const r=await f.adapter.execute(changed);assert.equal(r.status,'unknown');assert.match(r.reason,/reused/);assert.equal(f.state.writes.filter(x=>x.type==='pr').length,1)});

test('read-only reconciliation works while cancelled and safely recovers a dead local lock',async t=>{const f=fixture(t);f.state.failCreateAfter=true;const q=f.request('pull_request');await f.adapter.execute(q);fs.writeFileSync(path.join(f.config.controlDir,'CANCEL'),'stop');const lock=path.join(f.config.controlDir,'github-operations',digest(q.id)+'.json.lock');fs.mkdirSync(lock);fs.writeFileSync(path.join(lock,'owner.json'),JSON.stringify({pid:2147483647,hostname:os.hostname()}));const r=await f.adapter.execute({kind:'reconcile',operation:q});assert.equal(r.status,'succeeded');assert.equal(f.state.writes.filter(x=>x.type==='pr').length,1);assert.equal(fs.existsSync(lock),false)});
test('live lock owner cannot be displaced by reconciliation',async t=>{const f=fixture(t),q=f.request('pull_request');const dir=path.join(f.config.controlDir,'github-operations');fs.mkdirSync(dir);const lock=path.join(dir,digest(q.id)+'.json.lock');fs.mkdirSync(lock);fs.writeFileSync(path.join(lock,'owner.json'),JSON.stringify({pid:process.pid,hostname:os.hostname()}));await assert.rejects(f.adapter.execute({kind:'reconcile',operation:q}),/alive/);assert.equal(f.state.calls.length,0)});

test('live merge rejects unmeasured or bypassable server protection before writing',async t=>{for(const [key,value] of [['protectionStrict',false],['admin',true],['bypass',true],['policyCheckApp',99],['role','custom-maintainer']]){const f=fixture(t);await f.adapter.execute(f.request('pull_request'));f.state[key]=value;const r=await f.adapter.execute(f.request('merge'));assert.equal(r.status,'failed');assert.equal(f.state.writes.filter(x=>x.type==='merge').length,0)}});
test('protected token file is host-only, private, regular and never part of a receipt',async t=>{const f=fixture(t);const file=path.join(f.config.controlDir,'github-token');const secret='test_token_do_not_disclose_123';fs.writeFileSync(file,secret,{mode:0o600});const config={...f.config,github:{...f.config.github,tokenFile:file}};const adapter=createAdapter(config,{command:async(_bin,_args,{env})=>{assert.equal(env.GH_TOKEN,secret);throw Error('fixture fails safely')}});const r=await adapter.execute(f.request('pull_request'));assert.equal(JSON.stringify(r).includes(secret),false);fs.chmodSync(file,0o644);assert.throws(()=>createAdapter(config),/private/);fs.chmodSync(file,0o600);const link=path.join(f.config.controlDir,'token-link');fs.symlinkSync(file,link);assert.throws(()=>createAdapter({...config,github:{...config.github,tokenFile:link}}),/regular/);const external=path.join(os.tmpdir(),'outside-'+path.basename(f.config.controlDir));fs.writeFileSync(external,secret,{mode:0o600});t.after(()=>fs.rmSync(external,{force:true}));assert.throws(()=>createAdapter({...config,github:{...config.github,tokenFile:external}}),/control-root/)});
test('command timeout leaves process-tree cleanup to the inherited wrapper group',async()=>{await assert.rejects(runCommand(process.execPath,['-e','setTimeout(()=>{},10000)'],{env:{PATH:'/usr/bin:/bin'},timeoutSeconds:0.01}),e=>e.childStopUnproved===true)});

test('policy reader token is confined to policy GETs and never used for Git or write calls',async t=>{const f=fixture(t),tokenFile=path.join(f.config.controlDir,'writer-token'),policyTokenFile=path.join(f.config.controlDir,'policy-token');const writer='writer_secret_123456',reader='reader_secret_123456';fs.writeFileSync(tokenFile,writer,{mode:0o600});fs.writeFileSync(policyTokenFile,reader,{mode:0o600});const seen=[];const adapter=createAdapter({...f.config,github:{...f.config.github,tokenFile,policyTokenFile}},{command:async(bin,args,options)=>{const endpoint=args.find(x=>x.startsWith('/repos/'));const policy=endpoint&&(endpoint.endsWith('/protection')||endpoint.endsWith('/permission'));assert.equal(options.env.GH_TOKEN,policy?reader:writer);if(policy)assert.equal(args[args.indexOf('--method')+1],'GET');seen.push({policy:!!policy,bin,args});const clean={...options,env:{...options.env}};delete clean.env.GH_TOKEN;return f.command(bin,args,clean)}});const preflight=await adapter.preflight();assert.equal(preflight.mergeProtection.verified,true);const pr=await adapter.execute(f.request('pull_request'));assert.equal(pr.status,'succeeded');const merge=await adapter.execute(f.request('merge'));assert.equal(merge.status,'succeeded');assert(seen.some(x=>x.policy));assert(seen.some(x=>x.args.includes('PUT')));assert(!JSON.stringify({preflight,pr,merge}).includes(writer));assert(!JSON.stringify({preflight,pr,merge}).includes(reader))});
test('unproved command child cleanup never becomes a no-effect retry receipt',async t=>{const f=fixture(t);const adapter=createAdapter(f.config,{command:async()=>{const e=Error('command timeout');e.childStopUnproved=true;throw e}});const r=await adapter.execute(f.request('pull_request'));assert.equal(r.status,'unknown');assert.equal(r.allChildrenStopped,false)});
