import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {canonical,digest,executionProfileDigest} from '../lib/core.mjs';
import {compileMigration,validateReleaseConfig,verifyProductionApproval,preflight,execute,reconcile} from '../adapters/local-release.mjs';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const roles=['api','gateway','worker'];
function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'oxagen-release-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.chmodSync(root,0o700);
 const file=(n,b)=>{const p=path.join(root,n);fs.writeFileSync(p,b,{mode:0o600});return p};
 const keys=crypto.generateKeyPairSync('ed25519'),pub=file('approval.pub',keys.publicKey.export({type:'spki',format:'pem'}));
 const plan={version:1,id:'add-note',operations:[{kind:'add_nullable_column',table:'customers',column:'note',type:'text'}]},bytes=JSON.stringify(plan);
 const src=path.join(root,'src');fs.mkdirSync(src);const git=args=>execFileSync('/usr/bin/git',args,{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();git(['init',src]);git(['-C',src,'config','user.email','fixture@example.invalid']);git(['-C',src,'config','user.name','Fixture']);fs.mkdirSync(path.join(src,'release'));fs.writeFileSync(path.join(src,'release','migration.json'),bytes);git(['-C',src,'add','.']);git(['-C',src,'commit','-m','Fixture']);const head=git(['-C',src,'rev-parse','HEAD']);git(['clone','--bare',src,path.join(root,'product.git')]);
 const c={adapter:'local',controlDir:root,targets:{staging:'stage',production:'prod'},models:{},local:{deployment:{enabled:true,provider:'aws-ecs-fargate',aws:{command:'/fixture/aws',version:'2.36.45',homeDir:root,configFile:file('aws-config',''),credentialsFile:file('aws-credentials','')},timeoutSeconds:7200,pollSeconds:1,migration:{path:'release/migration.json',sha256:hash(bytes)},productionApproval:{publicKeyFile:pub,approvalFile:path.join(root,'approval.json')},targets:{}}}};
 const cloud={calls:[],locks:{},clusters:{},snapshots:{},definitions:{},services:{},tasks:{},journals:{},transactions:{},columns:{},counter:0};
 for(const [n,accountId] of [['staging','111111111111'],['production','222222222222']]){const region='us-east-1',role=name=>`arn:aws:iam::${accountId}:role/${name}`,clusterArn=`arn:aws:ecs:${region}:${accountId}:cluster/oxagen`,dbArn=`arn:aws:rds:${region}:${accountId}:cluster:oxagen-${n}`;
  const target={id:c.targets[n],accountId,region,profile:n,deploymentRoleArn:role('Deploy'),clusterArn,lockTable:'release-lock',releaseScope:'oxagen-'+n,namePrefix:'oxagen',services:{},healthUrls:['https://'+n+'.example.invalid/health/ready'],database:{identifier:'oxagen-'+n,arn:dbArn,secretArn:`arn:aws:secretsmanager:${region}:${accountId}:secret:master`,name:'oxagen',engineVersion:'16.4',kmsKeyArn:`arn:aws:kms:${region}:${accountId}:key/key`},rehearsal:{subnetGroup:'private',securityGroupIds:['sg-111'],taskSecurityGroupIds:['sg-222'],subnetIds:['subnet-111'],taskRoleArn:role('Probe'),executionRoleArn:role('ProbeExec'),logGroup:'/oxagen/probes',taskFamily:'oxagen-'+n+'-compatibility',minCapacity:0.5,maxCapacity:2}};
  c.local.deployment.targets[n]=target;cloud.services[n]={};cloud.clusters[n]={};cloud.clusters[n][target.database.identifier]={DBClusterIdentifier:target.database.identifier,DBClusterArn:dbArn,Engine:'aurora-postgresql',EngineVersion:'16.4',StorageEncrypted:true,KmsKeyId:target.database.kmsKeyArn,HttpEndpointEnabled:true,MasterUserSecret:{SecretArn:target.database.secretArn,SecretStatus:'active'},Status:'available',DBClusterMembers:[{DBInstanceIdentifier:'source',IsClusterWriter:true}]};cloud.columns[dbArn]=[['customers','id','uuid','NO','']];cloud.journals[dbArn]=[];
  for(const r of roles){const s={name:r,containerName:r,taskRoleArn:role(r),executionRoleArn:role('Exec'),databaseSecretArn:`arn:aws:secretsmanager:${region}:${accountId}:secret:${r}-app`,compatibilityCommand:['/app/check-schema',r]},ref=`arn:aws:ecs:${region}:${accountId}:task-definition/${r}:1`;target.services[r]=s;cloud.definitions[ref]={taskDefinitionArn:ref,family:r,taskRoleArn:s.taskRoleArn,executionRoleArn:s.executionRoleArn,networkMode:'awsvpc',requiresCompatibilities:['FARGATE'],cpu:'256',memory:'512',containerDefinitions:[{name:r,user:'10001:10001',readonlyRootFilesystem:true,essential:true,image:`${accountId}.dkr.ecr.${region}.amazonaws.com/${r}@sha256:${'a'.repeat(64)}`,healthCheck:{command:['CMD','/app/health']},environmentFiles:[{value:'must-be-stripped',type:'s3'}]}]};cloud.services[n][r]={serviceName:r,clusterArn,status:'ACTIVE',deploymentController:{type:'ECS'},launchType:'FARGATE',networkConfiguration:{awsvpcConfiguration:{assignPublicIp:'DISABLED'}},desiredCount:1,runningCount:1,pendingCount:0,taskDefinition:ref,deployments:[{rolloutState:'COMPLETED'}],loadBalancers:[]};}
 }
 let now=Date.now();const records=r=>({records:r.map(row=>row.map(v=>typeof v==='string'?{stringValue:v}:v===null?{isNull:true}:{longValue:v}))});
 const run=async(cmd,args,opts)=>{assert.equal(cmd,'/fixture/aws');assert.equal(opts.env.AWS_MAX_ATTEMPTS,'1');assert.equal(opts.env.AWS_IGNORE_CONFIGURED_ENDPOINT_URLS,'true');if(args[0]==='--version')return {exitCode:0,stdout:'aws-cli/2.36.45 Python/3 Linux/6',stderr:''};const n=args[args.indexOf('--profile')+1],target=c.local.deployment.targets[n],svc=args[0],verb=args[1],v=JSON.parse(args[args.indexOf('--cli-input-json')+1]);cloud.calls.push({n,svc,verb,v});if(cloud.before)await cloud.before({n,svc,verb,v});let out={};
  if(svc==='sts')out={Account:cloud.wrongAccount?'999999999999':target.accountId,Arn:`arn:aws:sts::${target.accountId}:assumed-role/Deploy/session`};
  else if(svc==='dynamodb'){if(verb==='describe-table')out={Table:{KeySchema:[{AttributeName:'release_scope',KeyType:'HASH'}]}};else if(verb==='put-item'){assert(!cloud.locks[n],'Conditional lock failed');cloud.locks[n]=v.Item;}else if(verb==='get-item')out=cloud.locks[n]?{Item:cloud.locks[n]}:{};else if(verb==='delete-item'){assert.equal(cloud.locks[n]?.owner.S,v.ExpressionAttributeValues[':owner'].S);delete cloud.locks[n];if(cloud.loseUnlock===n){cloud.loseUnlock=null;throw Error('Lost lock deletion reply')}}}
  else if(svc==='rds'){
   if(verb==='describe-db-clusters')out=cloud.badCloneList&&!v.DBClusterIdentifier?{}:{DBClusters:v.DBClusterIdentifier?[cloud.clusters[n][v.DBClusterIdentifier]].filter(Boolean):Object.values(cloud.clusters[n])};
   else if(verb==='create-db-cluster-snapshot'){cloud.snapshots[v.DBClusterSnapshotIdentifier]={DBClusterIdentifier:v.DBClusterIdentifier,StorageEncrypted:true,KmsKeyId:target.database.kmsKeyArn,Status:'available',DBClusterSnapshotArn:`arn:aws:rds:${target.region}:${target.accountId}:cluster-snapshot:${v.DBClusterSnapshotIdentifier}`,SnapshotCreateTime:new Date(now).toISOString()};}
   else if(verb==='describe-db-cluster-snapshots')out={DBClusterSnapshots:[cloud.snapshots[v.DBClusterSnapshotIdentifier]]};
   else if(verb==='restore-db-cluster-from-snapshot'){const ar=`arn:aws:rds:${target.region}:${target.accountId}:cluster:${v.DBClusterIdentifier}`;cloud.clusters[n][v.DBClusterIdentifier]={DBClusterIdentifier:v.DBClusterIdentifier,DBClusterArn:ar,Engine:'aurora-postgresql',Status:'available',StorageEncrypted:true,Endpoint:'clone.internal',DBClusterMembers:[],tags:v.Tags};cloud.columns[ar]=structuredClone(cloud.columns[target.database.arn]);cloud.journals[ar]=structuredClone(cloud.journals[target.database.arn]);}
   else if(verb==='create-db-instance')cloud.clusters[n][v.DBClusterIdentifier].DBClusterMembers=[{DBInstanceIdentifier:v.DBInstanceIdentifier,IsClusterWriter:true}];
   else if(verb==='modify-db-cluster')cloud.clusters[n][v.DBClusterIdentifier].MasterUserSecret={SecretArn:`arn:aws:secretsmanager:${target.region}:${target.accountId}:secret:clone`,SecretStatus:'active'};
   else if(verb==='enable-http-endpoint')out={ResourceArn:v.ResourceArn,HttpEndpointEnabled:true};
   else if(verb==='list-tags-for-resource')out={TagList:Object.values(cloud.clusters[n]).find(z=>z.DBClusterArn===v.ResourceName).tags};
   else if(verb==='delete-db-instance')for(const z of Object.values(cloud.clusters[n]))z.DBClusterMembers=z.DBClusterMembers.filter(i=>i.DBInstanceIdentifier!==v.DBInstanceIdentifier);
   else if(verb==='delete-db-cluster')delete cloud.clusters[n][v.DBClusterIdentifier];
   else throw Error('Unhandled RDS '+verb);
  }else if(svc==='rds-data'){
   if(verb==='begin-transaction'){const tx='tx'+ ++cloud.counter;cloud.transactions[tx]={arn:v.resourceArn,columns:structuredClone(cloud.columns[v.resourceArn]),journal:structuredClone(cloud.journals[v.resourceArn])};out={transactionId:tx};}
   else if(verb==='commit-transaction'){const tx=cloud.transactions[v.transactionId];cloud.columns[tx.arn]=tx.columns;cloud.journals[tx.arn]=tx.journal;out=cloud.badCommit?{}:{transactionStatus:'Transaction Committed'};}
   else if(verb==='execute-statement'){const tx=cloud.transactions[v.transactionId],columns=tx?.columns||cloud.columns[v.resourceArn],journal=tx?.journal||cloud.journals[v.resourceArn],params=Object.fromEntries((v.parameters||[]).map(z=>[z.name,z.value.stringValue]));
    if(v.sql.startsWith('SELECT c.relowner'))out={records:[[{booleanValue:!cloud.unsafeJournal}]]};
    else if(v.sql.startsWith('SELECT table_name'))out=cloud.badSelect?{}:records(columns);
    else if(v.sql.startsWith('SELECT execution_head'))out=records(journal.filter(z=>z.digest===params.digest&&(!params.artifact||z.artifact===params.artifact)).map(z=>[z.head,z.artifact]));
    else if(v.sql.startsWith('ALTER TABLE public."customers" ADD COLUMN'))columns.push(['customers','note','text','YES','']);
    else if(v.sql.startsWith('INSERT INTO public.oxagen_release_migrations'))journal.push(params);
    else if(!v.sql.startsWith('SET LOCAL')&&!v.sql.startsWith('CREATE TABLE IF NOT EXISTS')&&!v.sql.startsWith('REVOKE ALL ON TABLE'))throw Error('Unhandled SQL '+v.sql);
   }else throw Error('Unhandled data '+verb);
  }else if(svc==='ecs'){
   if(verb==='describe-services')out={services:[cloud.services[n][v.services[0]]]};
   else if(verb==='describe-task-definition')out={taskDefinition:cloud.definitions[v.taskDefinition]};
   else if(verb==='register-task-definition'){const ar=`arn:aws:ecs:${target.region}:${target.accountId}:task-definition/${v.family}:${++cloud.counter}`;cloud.definitions[ar]={...v,taskDefinitionArn:ar};out={taskDefinition:cloud.definitions[ar]};}
   else if(verb==='run-task'){const ar='arn:task:'+ ++cloud.counter;cloud.tasks[ar]={taskArn:ar,taskDefinitionArn:v.taskDefinition,lastStatus:cloud.slowProbe?'RUNNING':'STOPPED',containers:[{exitCode:cloud.failProbe?1:0}]};out={tasks:[{taskArn:ar}]};}
   else if(verb==='describe-tasks')out=cloud.badHealth&&v.tasks[0].startsWith('running:')?{tasks:[]}:{tasks:v.tasks.map(ar=>cloud.tasks[ar]||{taskArn:ar,taskDefinitionArn:cloud.services[n][ar.split(':').pop()].taskDefinition,lastStatus:'RUNNING',healthStatus:'HEALTHY',containers:[{name:ar.split(':').pop(),healthStatus:'HEALTHY'}]})};
   else if(verb==='stop-task'){cloud.tasks[v.task].lastStatus='STOPPED';out={task:cloud.tasks[v.task]};}
   else if(verb==='update-service'){cloud.services[n][v.service].taskDefinition=v.taskDefinition;cloud.services[n][v.service].deployments=[{rolloutState:cloud.failedRollout?'FAILED':'COMPLETED'}];out={service:cloud.services[n][v.service]};if(cloud.loseUpdate===v.service){cloud.loseUpdate=null;throw Error('Lost UpdateService response')}}
   else if(verb==='list-tasks')out={taskArns:['running:'+v.serviceName]};else throw Error('Unhandled ECS '+verb);
  }else throw Error('Unhandled AWS '+svc+' '+verb);
  return {exitCode:0,stdout:JSON.stringify(out),stderr:''};
 };
 const buildArtifact=async q=>{const body={version:1,executionHead:head,sourceTree:'tree',images:Object.fromEntries(roles.map(r=>[r,{digest:'sha256:'+'b'.repeat(64),uris:Object.fromEntries(['staging','production'].map(n=>[n,`${c.local.deployment.targets[n].accountId}.dkr.ecr.us-east-1.amazonaws.com/${r}@sha256:${'b'.repeat(64)}`]))}])),provenance:{profileDigest:executionProfileDigest(c)}};return {...body,artifactDigest:digest(body)}};
 const deps={run,now:()=>now,sleep:async ms=>{now+=ms},buildArtifact,fetch:async()=>({status:cloud.httpFailed?503:200})};
 const receipts={},request=(kind,name=kind)=>({id:name.replaceAll('_','-'),kind,maxCostCents:0,timeoutSeconds:7200,payload:{head,executionHead:head,targets:c.targets,previousReceipts:{post_merge_ci:{checkedHead:head,requiredChecksPassed:true},...receipts}}});
 const stage=async kind=>{const q=request(kind),r=await execute(q,c,deps);receipts[kind]=r;return r};
 const sign=(expiry=now+3600000)=>{const r=receipts.release_preflight,body={executionHead:head,artifactDigest:r.artifactDigest,target:c.targets.production,releaseId:r.releaseId,expiresAt:new Date(expiry).toISOString(),nonce:'fixture-unique-nonce'};const signature=crypto.sign(null,Buffer.from(canonical(body)),keys.privateKey).toString('base64');file('approval.json',canonical({body,signature}));return body};
 return {root,c,cloud,deps,head,receipts,request,stage,sign,advance:ms=>{now+=ms},keys};
}

test('constrained migration compiles additive changes with new-table RLS and rejects unsafe SQL',()=>{
 const sql=compileMigration({version:1,id:'new',operations:[{kind:'create_table',table:'notes',columns:[{name:'id',type:'uuid'}],primaryKey:['id']},{kind:'create_index',name:'note_id',table:'notes',columns:['id']}]});assert(sql.some(x=>x.includes('FORCE ROW LEVEL SECURITY')));assert(sql.some(x=>x.includes('REVOKE ALL')));for(const op of [{kind:'sql',sql:'DROP TABLE customers'},{kind:'add_nullable_column',table:'customers',column:'x;DROP',type:'text'},{kind:'add_nullable_column',table:'customers',column:'x',type:'text',default:'secret'}])assert.throws(()=>compileMigration({version:1,id:'bad',operations:[op]}));
});
test('configuration requires separate accounts, private authority files and restricted rehearsal roles',t=>{const f=fixture(t);validateReleaseConfig(f.c);f.c.local.deployment.targets.production.accountId='111111111111';assert.throws(()=>validateReleaseConfig(f.c));});
test('read-only preflight verifies pinned CLI, accounts, database and task bindings',async t=>{const f=fixture(t);assert.equal((await preflight(f.c,f.deps)).verified,true);assert(!f.cloud.calls.some(x=>x.verb.startsWith('create')||x.verb==='put-item'));f.cloud.wrongAccount=true;await assert.rejects(preflight(f.c,f.deps),/account mismatch/);});
test('migration bytes must match exact merged commit before artifact build or AWS writes',async t=>{const f=fixture(t);f.c.local.deployment.migration.sha256='c'.repeat(64);await assert.rejects(f.stage('release_preflight'),/Migration bytes/);assert.equal(f.cloud.calls.length,0);});
test('full fixture release snapshots, rehearses new then old, migrates and conditionally frees locks',async t=>{const f=fixture(t);const p=await f.stage('release_preflight');assert(p.backupVerified&&p.migrationsRehearsed&&p.rollbackReady);assert.equal(Object.keys(f.cloud.locks).length,2);const probes=f.cloud.calls.filter(z=>z.verb==='register-task-definition');assert.equal(probes.length,12);assert(probes.slice(0,3).every(z=>z.v.containerDefinitions[0].image.endsWith('b'.repeat(64))));assert(probes.slice(3,6).every(z=>z.v.containerDefinitions[0].image.endsWith('a'.repeat(64))));for(const z of probes){assert(!z.v.containerDefinitions[0].environmentFiles);assert(z.v.executionRoleArn.endsWith('/ProbeExec'));assert.equal(z.v.containerDefinitions[0].secrets.length,2);assert(z.v.containerDefinitions[0].secrets[0].valueFrom.endsWith(':username::'))}assert.equal(Object.keys(f.cloud.clusters.staging).length,1);await f.stage('staging_deploy');assert.equal((await f.stage('staging_health')).healthy,true);f.sign();await f.stage('production_authorize');await f.stage('production_deploy');assert.equal((await f.stage('production_health')).healthy,true);assert.deepEqual(f.cloud.locks,{});const updates=f.cloud.calls.filter(z=>z.verb==='update-service');assert.equal(updates.length,6);assert(updates.every(z=>z.v.deploymentConfiguration.deploymentCircuitBreaker.rollback===false));});
test('failed real schema probe retains locks and does not claim qualification',async t=>{const f=fixture(t);f.cloud.failProbe=true;await assert.rejects(f.stage('release_preflight'),/compatibility check failed/);assert(f.cloud.locks.staging);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,0);await assert.rejects(execute(f.request('release_preflight'),f.c,f.deps),/reconciled/);});
test('a lost final ECS update is adopted read-only after exact AWS state and migration journal checks',async t=>{const f=fixture(t);await f.stage('release_preflight');f.cloud.loseUpdate='worker';const q=f.request('staging_deploy');await assert.rejects(execute(q,f.c,f.deps),/Lost UpdateService/);const count=f.cloud.calls.filter(z=>z.verb==='update-service').length;const recovered=await reconcile(q,f.c,f.deps);assert.equal(recovered.completedReceipt.recovered,true);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,count);});
test('partial deploy with unattempted remaining services never auto-replays',async t=>{const f=fixture(t);await f.stage('release_preflight');f.cloud.loseUpdate='api';const q=f.request('staging_deploy');await assert.rejects(execute(q,f.c,f.deps));await assert.rejects(reconcile(q,f.c,f.deps),/Partial deployment/);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,1);});
test('pending manual production approval can be supplied and reconciled without deleting history',async t=>{const f=fixture(t);await f.stage('release_preflight');await f.stage('staging_deploy');await f.stage('staging_health');const q=f.request('production_authorize');await assert.rejects(execute(q,f.c,f.deps));f.sign();const r=await reconcile(q,f.c,f.deps);assert.equal(r.completedReceipt.authorized,true);assert.equal(r.completedReceipt.executionHead,f.head);});
test('approval expiry during snapshot work blocks later production mutations',async t=>{const f=fixture(t);await f.stage('release_preflight');await f.stage('staging_deploy');await f.stage('staging_health');f.sign();await f.stage('production_authorize');f.cloud.before=async({n,verb})=>{if(n==='production'&&verb==='describe-db-cluster-snapshots')f.advance(3600001)};await assert.rejects(f.stage('production_deploy'),/approval is missing, expired/);assert.equal(f.cloud.calls.filter(z=>z.n==='production'&&z.verb==='update-service').length,0);assert(f.cloud.locks.production);});
test('confirmed failed health restores captured old definitions, preserves schema and releases locks',async t=>{const f=fixture(t);await f.stage('release_preflight');await f.stage('staging_deploy');f.cloud.httpFailed=true;const bad=await f.stage('staging_health');assert.equal(bad.healthy,false);f.cloud.httpFailed=false;const q={id:'rollback-1',kind:'rollback',maxCostCents:0,timeoutSeconds:7200,payload:{head:f.head,executionHead:f.head,targets:f.c.targets,receipts:f.receipts,failedHealth:bad}};const r=await execute(q,f.c,f.deps);assert(r.restored&&r.healthy&&r.schemaRetained);assert.equal(r.target,'stage');assert.deepEqual(f.cloud.locks,{});for(const role of roles)assert(f.cloud.services.staging[role].taskDefinition.endsWith(':1'));});
test('approval signatures bind the exact artifact and target',async t=>{const f=fixture(t);await f.stage('release_preflight');f.sign();const r=JSON.parse(fs.readFileSync(path.join(f.root,'aws-release','release-release-preflight.json')));assert(verifyProductionApproval(f.c,r));r.artifactDigest='f'.repeat(64);assert.throws(()=>verifyProductionApproval(f.c,r),/another release/);});

test('lost final lock deletion is adopted without repeating writes',async t=>{const f=fixture(t);await f.stage('release_preflight');await f.stage('staging_deploy');await f.stage('staging_health');f.sign();await f.stage('production_authorize');await f.stage('production_deploy');f.cloud.loseUnlock='production';const q=f.request('production_health');await assert.rejects(execute(q,f.c,f.deps),/Lost lock deletion/);const count=f.cloud.calls.filter(z=>z.verb==='delete-item').length;const r=await reconcile(q,f.c,f.deps);assert(r.completedReceipt.healthy&&r.completedReceipt.recovered);assert.equal(f.cloud.calls.filter(z=>z.verb==='delete-item').length,count);});
test('missing health task records remain unconfirmed and keep locks',async t=>{const f=fixture(t);await f.stage('release_preflight');await f.stage('staging_deploy');f.cloud.badHealth=true;const q=f.request('staging_health');q.timeoutSeconds=2;await assert.rejects(execute(q,f.c,f.deps),/Health evidence is incomplete/);assert(f.cloud.locks.staging&&f.cloud.locks.production);});
test('later stages cannot change the merged source identity',async t=>{const f=fixture(t);await f.stage('release_preflight');const q=f.request('staging_deploy');q.payload.executionHead='f'.repeat(40);await assert.rejects(execute(q,f.c,f.deps),/Release evidence/);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,0);});

test('a timed out probe gets a bounded explicit stop and remains a failed held release',async t=>{const f=fixture(t);f.cloud.slowProbe=true;const q=f.request('release_preflight');q.timeoutSeconds=70;await assert.rejects(execute(q,f.c,f.deps),/task stop is confirmed/);assert.equal(f.cloud.calls.filter(z=>z.verb==='stop-task').length,1);assert(f.cloud.locks.staging);assert(Object.values(f.cloud.tasks).every(z=>z.lastStatus==='STOPPED'));});

test('a journal write grant to an application role blocks migration proof',async t=>{const f=fixture(t);f.cloud.unsafeJournal=true;await assert.rejects(f.stage('release_preflight'),/journal must be owned/);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,0);});

test('malformed SELECT, commit and clone deletion replies never become proof',async t=>{for(const flag of ['badSelect','badCommit','badCloneList']){const f=fixture(t);f.cloud[flag]=true;await assert.rejects(f.stage('release_preflight'),/Malformed Data API SELECT|commit outcome is unconfirmed|Malformed cluster deletion/);assert.equal(f.cloud.calls.filter(z=>z.verb==='update-service').length,0);assert(f.cloud.locks.staging)}});

test('private nonroot bounded runtime and healthy baseline are required',async t=>{for(const flag of ['public','root','replicas','unhealthy','inflight']){const f=fixture(t),s=f.cloud.services.staging.api,def=f.cloud.definitions[s.taskDefinition];if(flag==='public')s.networkConfiguration.awsvpcConfiguration.assignPublicIp='ENABLED';if(flag==='root')def.user='0';if(flag==='root')def.containerDefinitions[0].user='0';if(flag==='replicas')s.desiredCount=7;if(flag==='unhealthy')f.cloud.httpFailed=true;if(flag==='inflight')s.pendingCount=1;await assert.rejects(f.stage('release_preflight'),/private bounded|pinned-image|health is not confirmed|stable service/);assert.equal(f.cloud.calls.filter(z=>z.verb==='create-db-cluster-snapshot').length,0)}});
