"""Generate the checked-in native CloudFormation JSON. Does not call AWS."""
from pathlib import Path
import json
OUT=Path(__file__).resolve().parent
R=lambda x:{'Ref':x}
A=lambda x,y:{'Fn::GetAtt':[x,y]}
S=lambda x:{'Fn::Sub':x}
IF=lambda c,a,b:{'Fn::If':[c,a,b]}
NO=R('AWS::NoValue')
def param(t='String',**kw):return dict(Type=t,**kw)
def res(t,p,**kw):return dict(Type=t,Properties=p,**kw)
def policy(statements):return {'Version':'2012-10-17','Statement':statements}
def allow(actions,resources,**kw):return dict(Effect='Allow',Action=actions,Resource=resources,**kw)
def out(value,description):return dict(Value=value,Description=description)
def write(name,d):(OUT/name).write_text(json.dumps(d,indent=2)+'\n')
base={'AWSTemplateFormatVersion':'2010-09-09'}
P={
'NamePrefix':param(AllowedPattern='[a-z][a-z0-9-]{1,15}'),'Environment':param(AllowedValues=['staging','production']),
'VpcId':param('AWS::EC2::VPC::Id'),'PublicSubnetIds':param('List<AWS::EC2::Subnet::Id>'),'PrivateSubnetIds':param('List<AWS::EC2::Subnet::Id>'),
'IngressCidr':param(Description='Explicit operator-approved IPv4 client range; 0.0.0.0/0 is an intentional public choice.'),'ApprovedGatewayEgressCidr':param(Description='HTTPS provider/proxy egress range through the existing controlled private-subnet route.'),
'CertificateArn':param(AllowedPattern='arn:[^:]+:acm:[^:]+:[0-9]{12}:certificate/.+'),'PublicHostname':param(AllowedPattern='[A-Za-z0-9.-]+',Description='Existing DNS name covered by the ACM certificate; operator creates its ALB alias.'),
'ImageRepositoryUri':param(AllowedPattern='[0-9]{12}\\.dkr\\.ecr\\.[a-z0-9-]+\\.[a-z0-9.]+/[a-z0-9/_-]+'),'ImageRepositoryArn':param(AllowedPattern='arn:[^:]+:ecr:[^:]+:[0-9]{12}:repository/.+'),'ImageDigest':param(AllowedPattern='sha256:[a-f0-9]{64}'),
'DataKmsKeyArn':param(AllowedPattern='arn:[^:]+:kms:[^:]+:[0-9]{12}:key/.+'),'LogsKmsKeyArn':param(AllowedPattern='arn:[^:]+:kms:[^:]+:[0-9]{12}:key/.+'),
'PostgresEngineVersion':param(Description='Operator-selected Aurora PostgreSQL release supporting Serverless v2 and Data API in this region.'),'PostgresParameterFamily':param(AllowedPattern='aurora-postgresql[0-9]+',Description='Family matching the engine major version.'),
'ApiRuntimeSecretArn':param(AllowedPattern='arn:[^:]+:secretsmanager:[^:]+:[0-9]{12}:secret:.+'),'GatewayRuntimeSecretArn':param(AllowedPattern='arn:[^:]+:secretsmanager:[^:]+:[0-9]{12}:secret:.+'),'WorkerRuntimeSecretArn':param(AllowedPattern='arn:[^:]+:secretsmanager:[^:]+:[0-9]{12}:secret:.+'),
'ControllerPrincipalArn':param(AllowedPattern='arn:[^:]+:iam::[0-9]{12}:role/.+',Description='Existing protected controller role allowed to assume this environment deployment role.'),
'GitHubOidcProviderArn':param(Default='',Description='Optional existing token.actions.githubusercontent.com IAM OIDC provider ARN.'),'GitHubRepository':param(Default='',AllowedPattern='|[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+'),
'ApiDesiredCount':param('Number',Default=2,MinValue=1,MaxValue=6),'GatewayDesiredCount':param('Number',Default=2,MinValue=1,MaxValue=6),'WorkerDesiredCount':param('Number',Default=1,MinValue=1,MaxValue=4),
'DatabaseMinAcu':param('Number',Default=0.5,AllowedValues=[0.5,1,2]),'DatabaseMaxAcu':param('Number',Default=4,AllowedValues=[4,8,16]),
'MonthlyBudgetUsd':param('Number',MinValue=1,Description='Notification threshold only; does not stop AWS spending.'),'NotificationEmail':param(AllowedPattern='[^@ ]+@[^@ ]+\\.[^@ ]+'),
'BackupRetentionDays':param('Number',Default=14,MinValue=7,MaxValue=35),'LogRetentionDays':param('Number',Default=90,AllowedValues=[30,60,90,120,180,365,731]),
'BootstrapServicesEnabled':param(Default='true',AllowedValues=['true'],Description='Services require real pre-published baseline images; no placeholder image mode.')}
for role in ['Api','Gateway','Worker']:
 P[role+'ImageRepositoryUri']=P['ImageRepositoryUri'].copy();P[role+'ImageRepositoryArn']=P['ImageRepositoryArn'].copy();P[role+'ImageDigest']=P['ImageDigest'].copy()
 P[role+'DatabaseSecretArn']=param(AllowedPattern='arn:[^:]+:secretsmanager:[^:]+:[0-9]{12}:secret:.+',Description='Dedicated least-privilege DB user JSON; separate from runtime/provider credentials. Password is copied into snapshot clones.')
for old in ['ImageRepositoryUri','ImageRepositoryArn','ImageDigest','BootstrapServicesEnabled']:P.pop(old,None)
P['EnableServices']=param(Default='false',AllowedValues=['true','false'],Description='Keep tasks stopped until approved baseline images, scoped DB users, secrets and bootstrap migrations are ready.')
C={'RuntimeEnabled':{'Fn::Equals':[R('EnableServices'),'true']},'IsProduction':{'Fn::Equals':[R('Environment'),'production']},'UseGitHubOidc':{'Fn::Not':[{'Fn::Equals':[R('GitHubOidcProviderArn'),'']}]}}
tags=[{'Key':'Application','Value':'oxagen'},{'Key':'Environment','Value':R('Environment')},{'Key':'Stack','Value':R('AWS::StackName')}]
resources={}
def add(n,t,p,**kw):resources[n]=res(t,p,**kw);return R(n)
# Tasks are always private. Existing VPC/subnets and controlled egress are explicit inputs, checked by the setup script.
for name in ['AlbSecurityGroup','ApiSecurityGroup','GatewaySecurityGroup','WorkerSecurityGroup','DatabaseSecurityGroup','EndpointSecurityGroup']:
 add(name,'AWS::EC2::SecurityGroup',{'GroupDescription':'Oxagen '+name,'VpcId':R('VpcId'),'SecurityGroupEgress':[{'IpProtocol':'-1','CidrIp':'127.0.0.1/32','Description':'No default outbound permission'}],'Tags':tags})
add('AlbHttpsIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R('AlbSecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443,'CidrIp':R('IngressCidr')})
for role,port in [('Api',8080),('Gateway',8081)]:
 add(role+'AlbIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R(role+'SecurityGroup'),'IpProtocol':'tcp','FromPort':port,'ToPort':port,'SourceSecurityGroupId':R('AlbSecurityGroup')})
 add(role+'AlbEgress','AWS::EC2::SecurityGroupEgress',{'GroupId':R('AlbSecurityGroup'),'IpProtocol':'tcp','FromPort':port,'ToPort':port,'DestinationSecurityGroupId':R(role+'SecurityGroup')})
for role in ['Api','Gateway','Worker']:
 add(role+'DatabaseEgress','AWS::EC2::SecurityGroupEgress',{'GroupId':R(role+'SecurityGroup'),'IpProtocol':'tcp','FromPort':5432,'ToPort':5432,'DestinationSecurityGroupId':R('DatabaseSecurityGroup')})
 add(role+'DatabaseIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R('DatabaseSecurityGroup'),'IpProtocol':'tcp','FromPort':5432,'ToPort':5432,'SourceSecurityGroupId':R(role+'SecurityGroup')})
 add(role+'EndpointEgress','AWS::EC2::SecurityGroupEgress',{'GroupId':R(role+'SecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443,'DestinationSecurityGroupId':R('EndpointSecurityGroup')})
 add(role+'EndpointIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R('EndpointSecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443,'SourceSecurityGroupId':R(role+'SecurityGroup')})
add('GatewayProviderEgress','AWS::EC2::SecurityGroupEgress',{'GroupId':R('GatewaySecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443,'CidrIp':R('ApprovedGatewayEgressCidr')})
for logical,service in [('EcrApiEndpoint','ecr.api'),('EcrDockerEndpoint','ecr.dkr'),('LogsEndpoint','logs'),('MonitoringEndpoint','monitoring'),('SecretsEndpoint','secretsmanager'),('KmsEndpoint','kms'),('SqsEndpoint','sqs')]:
 add(logical,'AWS::EC2::VPCEndpoint',{'VpcEndpointType':'Interface','VpcId':R('VpcId'),'SubnetIds':R('PrivateSubnetIds'),'SecurityGroupIds':[R('EndpointSecurityGroup')],'PrivateDnsEnabled':True,'ServiceName':S('com.amazonaws.${AWS::Region}.'+service)})
# ECR layer downloads and artifact data use existing S3 gateway endpoint prefix list/routes.
P['S3PrefixListId']=param(AllowedPattern='pl-[0-9a-f]+',Description='AWS-managed S3 prefix list for this region; private subnet route tables must have an S3 gateway endpoint.')
for role in ['Api','Gateway','Worker']:
 add(role+'S3Egress','AWS::EC2::SecurityGroupEgress',{'GroupId':R(role+'SecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443,'DestinationPrefixListId':R('S3PrefixListId')})
add('DbSubnetGroup','AWS::RDS::DBSubnetGroup',{'DBSubnetGroupDescription':'Private Aurora subnets in at least two AZs','SubnetIds':R('PrivateSubnetIds'),'Tags':tags})
add('DbParameterGroup','AWS::RDS::DBClusterParameterGroup',{'Description':'Require TLS for application PostgreSQL connections','Family':R('PostgresParameterFamily'),'Parameters':{'rds.force_ssl':'1','log_statement':'none','log_min_error_statement':'panic'}})
add('DatabaseLogs','AWS::Logs::LogGroup',{'LogGroupName':S('/aws/rds/cluster/${NamePrefix}-${Environment}/postgresql'),'KmsKeyId':R('LogsKmsKeyArn'),'RetentionInDays':R('LogRetentionDays'),'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
add('Database','AWS::RDS::DBCluster',{'DBClusterIdentifier':S('${NamePrefix}-${Environment}'),'Engine':'aurora-postgresql','EngineMode':'provisioned','EngineVersion':R('PostgresEngineVersion'),'DatabaseName':'oxagen','MasterUsername':'oxagen_admin','ManageMasterUserPassword':True,'MasterUserSecret':{'KmsKeyId':R('DataKmsKeyArn')},'StorageEncrypted':True,'KmsKeyId':R('DataKmsKeyArn'),'DBSubnetGroupName':R('DbSubnetGroup'),'DBClusterParameterGroupName':R('DbParameterGroup'),'VpcSecurityGroupIds':[R('DatabaseSecurityGroup')],'EnableHttpEndpoint':True,'ServerlessV2ScalingConfiguration':{'MinCapacity':R('DatabaseMinAcu'),'MaxCapacity':R('DatabaseMaxAcu')},'BackupRetentionPeriod':R('BackupRetentionDays'),'CopyTagsToSnapshot':True,'DeletionProtection':True,'EnableCloudwatchLogsExports':['postgresql'],'Tags':tags},DependsOn='DatabaseLogs',DeletionPolicy='Snapshot',UpdateReplacePolicy='Snapshot')
for role in ['Writer','Reader']:
 add('Database'+role,'AWS::RDS::DBInstance',{'DBClusterIdentifier':R('Database'),'Engine':'aurora-postgresql','DBInstanceClass':'db.serverless','PubliclyAccessible':False,'AutoMinorVersionUpgrade':False,'PromotionTier':0 if role=='Writer' else 1,'Tags':tags},**({'Condition':'IsProduction'} if role=='Reader' else {}))
add('Artifacts','AWS::S3::Bucket',{'PublicAccessBlockConfiguration':{'BlockPublicAcls':True,'IgnorePublicAcls':True,'BlockPublicPolicy':True,'RestrictPublicBuckets':True},'OwnershipControls':{'Rules':[{'ObjectOwnership':'BucketOwnerEnforced'}]},'BucketEncryption':{'ServerSideEncryptionConfiguration':[{'ServerSideEncryptionByDefault':{'SSEAlgorithm':'aws:kms','KMSMasterKeyID':R('DataKmsKeyArn')},'BucketKeyEnabled':True}]},'VersioningConfiguration':{'Status':'Enabled'},'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
add('ArtifactPolicy','AWS::S3::BucketPolicy',{'Bucket':R('Artifacts'),'PolicyDocument':policy([{'Effect':'Deny','Principal':'*','Action':'s3:*','Resource':[A('Artifacts','Arn'),S('${Artifacts.Arn}/*')],'Condition':{'Bool':{'aws:SecureTransport':'false'}}}])})
add('DeadLetterQueue','AWS::SQS::Queue',{'KmsMasterKeyId':R('DataKmsKeyArn'),'MessageRetentionPeriod':1209600,'Tags':tags})
add('WorkQueue','AWS::SQS::Queue',{'KmsMasterKeyId':R('DataKmsKeyArn'),'VisibilityTimeout':300,'MessageRetentionPeriod':345600,'RedrivePolicy':{'deadLetterTargetArn':A('DeadLetterQueue','Arn'),'maxReceiveCount':5},'Tags':tags})
add('DeploymentLocks','AWS::DynamoDB::Table',{'BillingMode':'PAY_PER_REQUEST','AttributeDefinitions':[{'AttributeName':'release_scope','AttributeType':'S'}],'KeySchema':[{'AttributeName':'release_scope','KeyType':'HASH'}],'SSESpecification':{'SSEEnabled':True,'SSEType':'KMS','KMSMasterKeyId':R('DataKmsKeyArn')},'PointInTimeRecoverySpecification':{'PointInTimeRecoveryEnabled':True},'DeletionProtectionEnabled':True,'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
add('Cluster','AWS::ECS::Cluster',{'ClusterName':S('${NamePrefix}-${Environment}'),'ClusterSettings':[{'Name':'containerInsights','Value':'enabled'}],'Tags':tags})
add('Notifications','AWS::SNS::Topic',{'KmsMasterKeyId':R('DataKmsKeyArn'),'Subscription':[{'Protocol':'email','Endpoint':R('NotificationEmail')}],'Tags':tags})
# Task role trust is bound to this account; ECS uses task source ARNs, not the role itself.
trust=policy([{'Effect':'Allow','Principal':{'Service':'ecs-tasks.amazonaws.com'},'Action':'sts:AssumeRole','Condition':{'StringEquals':{'aws:SourceAccount':R('AWS::AccountId')},'ArnLike':{'aws:SourceArn':S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:*')}}}])
for role,port in [('Api',8080),('Gateway',8081),('Worker',0)]:
 add(role+'Logs','AWS::Logs::LogGroup',{'LogGroupName':S('/oxagen/${NamePrefix}/${Environment}/'+role.lower()),'KmsKeyId':R('LogsKmsKeyArn'),'RetentionInDays':R('LogRetentionDays'),'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
 execStatements=[allow(['ecr:GetAuthorizationToken'],'*',Condition={'StringEquals':{'aws:RequestedRegion':R('AWS::Region')}}),allow(['ecr:BatchCheckLayerAvailability','ecr:GetDownloadUrlForLayer','ecr:BatchGetImage'],R(role+'ImageRepositoryArn')),allow(['logs:CreateLogStream','logs:PutLogEvents'],A(role+'Logs','Arn')),allow(['secretsmanager:GetSecretValue'],[R(role+'RuntimeSecretArn'),R(role+'DatabaseSecretArn')]),allow(['kms:Decrypt'],R('DataKmsKeyArn'),Condition={'StringEquals':{'kms:ViaService':S('secretsmanager.${AWS::Region}.${AWS::URLSuffix}')}})]
 add(role+'ExecutionRole','AWS::IAM::Role',{'AssumeRolePolicyDocument':trust,'Policies':[{'PolicyName':'PullImageLogsAndOwnSecret','PolicyDocument':policy(execStatements)}],'Tags':tags})
 taskStatements=[allow(['s3:GetObject','s3:PutObject','s3:GetObjectVersion'],S('${Artifacts.Arn}/*')),allow(['s3:ListBucket'],A('Artifacts','Arn')),allow(['kms:Decrypt','kms:GenerateDataKey'],R('DataKmsKeyArn'))]
 if role=='Api':taskStatements.append(allow(['sqs:SendMessage','sqs:GetQueueAttributes'],A('WorkQueue','Arn')))
 if role=='Worker':taskStatements.append(allow(['sqs:ReceiveMessage','sqs:DeleteMessage','sqs:ChangeMessageVisibility','sqs:GetQueueAttributes'],A('WorkQueue','Arn')))
 # Application telemetry publishes only these namespaced metrics, not raw prompt text.
 taskStatements.append(allow(['cloudwatch:PutMetricData'],'*',Condition={'StringEquals':{'cloudwatch:namespace':'Oxagen/Runtime','aws:RequestedRegion':R('AWS::Region')}}))
 add(role+'TaskRole','AWS::IAM::Role',{'AssumeRolePolicyDocument':trust,'Policies':[{'PolicyName':'ScopedApplicationData','PolicyDocument':policy(taskStatements)}],'Tags':tags})
 container={'Name':role.lower(),'Image':S('${'+role+'ImageRepositoryUri}@${'+role+'ImageDigest}'),'Essential':True,'EntryPoint':['/opt/oxagen/bin/oxagen'],'Command':['serve',role.lower()],'ReadonlyRootFilesystem':True,'User':'10001:10001','LinuxParameters':{'InitProcessEnabled':True,'Capabilities':{'Drop':['ALL']}},'StopTimeout':60,'Environment':[{'Name':'OXAGEN_ENVIRONMENT','Value':R('Environment')},{'Name':'DB_HOST','Value':A('Database','Endpoint.Address')},{'Name':'DB_PORT','Value':'5432'},{'Name':'DB_NAME','Value':'oxagen'},{'Name':'DB_SSLMODE','Value':'verify-full'},{'Name':'ARTIFACT_BUCKET','Value':R('Artifacts')},{'Name':'WORK_QUEUE_URL','Value':R('WorkQueue')},{'Name':'RELEASE_IMAGE_DIGEST','Value':R(role+'ImageDigest')}],'Secrets':[{'Name':'OXAGEN_RUNTIME_CONFIG','ValueFrom':R(role+'RuntimeSecretArn')},{'Name':'DB_USER','ValueFrom':{'Fn::Join':['',[R(role+'DatabaseSecretArn'),':username::']]}},{'Name':'DB_PASSWORD','ValueFrom':{'Fn::Join':['',[R(role+'DatabaseSecretArn'),':password::']]}}],'LogConfiguration':{'LogDriver':'awslogs','Options':{'awslogs-group':R(role+'Logs'),'awslogs-region':R('AWS::Region'),'awslogs-stream-prefix':role.lower(),'mode':'non-blocking','max-buffer-size':'10m'}},'MountPoints':[{'SourceVolume':'temp','ContainerPath':'/tmp','ReadOnly':False}], 'HealthCheck':{'Command':['CMD','/opt/oxagen/bin/oxagen','health','--component',role.lower(),'--ready','--quiet'],'Interval':30,'Timeout':5,'Retries':3,'StartPeriod':30}}
 if port:container['PortMappings']=[{'ContainerPort':port,'Protocol':'tcp'}]
 add(role+'TaskDefinition','AWS::ECS::TaskDefinition',{'Family':S('${NamePrefix}-${Environment}-'+role.lower()),'Cpu':'512','Memory':'1024','NetworkMode':'awsvpc','RequiresCompatibilities':['FARGATE'],'RuntimePlatform':{'CpuArchitecture':'X86_64','OperatingSystemFamily':'LINUX'},'ExecutionRoleArn':A(role+'ExecutionRole','Arn'),'TaskRoleArn':A(role+'TaskRole','Arn'),'ContainerDefinitions':[container],'Volumes':[{'Name':'temp'}],'Tags':tags})
# TLS-only ALB, no automatic public DNS changes.
add('LoadBalancer','AWS::ElasticLoadBalancingV2::LoadBalancer',{'Scheme':'internet-facing','Type':'application','Subnets':R('PublicSubnetIds'),'SecurityGroups':[R('AlbSecurityGroup')],'LoadBalancerAttributes':[{'Key':'deletion_protection.enabled','Value':'true'},{'Key':'routing.http.drop_invalid_header_fields.enabled','Value':'true'},{'Key':'routing.http.desync_mitigation_mode','Value':'strictest'}],'Tags':tags})
for role,port in [('Api',8080),('Gateway',8081)]:
 add(role+'TargetGroup','AWS::ElasticLoadBalancingV2::TargetGroup',{'VpcId':R('VpcId'),'Port':port,'Protocol':'HTTP','TargetType':'ip','HealthCheckPath':'/health/ready','HealthCheckIntervalSeconds':30,'HealthyThresholdCount':2,'UnhealthyThresholdCount':3,'Matcher':{'HttpCode':'200'},'TargetGroupAttributes':[{'Key':'deregistration_delay.timeout_seconds','Value':'30'}],'Tags':tags})
add('HttpsListener','AWS::ElasticLoadBalancingV2::Listener',{'LoadBalancerArn':R('LoadBalancer'),'Port':443,'Protocol':'HTTPS','SslPolicy':'ELBSecurityPolicy-TLS13-1-2-2021-06','Certificates':[{'CertificateArn':R('CertificateArn')}],'DefaultActions':[{'Type':'forward','TargetGroupArn':R('ApiTargetGroup')}]})
add('GatewayRoute','AWS::ElasticLoadBalancingV2::ListenerRule',{'ListenerArn':R('HttpsListener'),'Priority':10,'Conditions':[{'Field':'path-pattern','Values':['/gateway/*']}],'Actions':[{'Type':'forward','TargetGroupArn':R('GatewayTargetGroup')}]})
for role in ['Api','Gateway','Worker']:
 add(role+'CpuAlarm','AWS::CloudWatch::Alarm',{'AlarmDescription':'Sustained ECS CPU pressure; capacity remains explicitly bounded','Namespace':'AWS/ECS','MetricName':'CPUUtilization','Dimensions':[{'Name':'ClusterName','Value':R('Cluster')},{'Name':'ServiceName','Value':S('${NamePrefix}-${Environment}-'+role.lower())}],'Statistic':'Average','Period':60,'EvaluationPeriods':5,'Threshold':90,'ComparisonOperator':'GreaterThanThreshold','TreatMissingData':'notBreaching','AlarmActions':[R('Notifications')]})
 add(role+'HeartbeatAlarm','AWS::CloudWatch::Alarm',{'AlarmDescription':'Application must publish one sanitized health heartbeat per minute for this exact role/environment','Namespace':'Oxagen/Runtime','MetricName':'HealthyHeartbeat','Dimensions':[{'Name':'Environment','Value':R('Environment')},{'Name':'Service','Value':role.lower()}],'Statistic':'Sum','Period':60,'EvaluationPeriods':3,'Threshold':1,'ComparisonOperator':'LessThanThreshold','TreatMissingData':'breaching','AlarmActions':[R('Notifications')]},Condition='RuntimeEnabled')
 svc={'ServiceName':S('${NamePrefix}-${Environment}-'+role.lower()),'Cluster':R('Cluster'),'TaskDefinition':R(role+'TaskDefinition'),'DesiredCount':IF('RuntimeEnabled',R(role+'DesiredCount'),0),'LaunchType':'FARGATE','PlatformVersion':'1.4.0','EnableExecuteCommand':False,'EnableECSManagedTags':True,'PropagateTags':'SERVICE','DeploymentController':{'Type':'ECS'},'DeploymentConfiguration':{'MinimumHealthyPercent':100,'MaximumPercent':200,'DeploymentCircuitBreaker':{'Enable':True,'Rollback':True}},'NetworkConfiguration':{'AwsvpcConfiguration':{'AssignPublicIp':'DISABLED','Subnets':R('PrivateSubnetIds'),'SecurityGroups':[R(role+'SecurityGroup')]}},'Tags':tags}
 if role!='Worker':svc.update(HealthCheckGracePeriodSeconds=90,LoadBalancers=[{'ContainerName':role.lower(),'ContainerPort':8080 if role=='Api' else 8081,'TargetGroupArn':R(role+'TargetGroup')}])
 add(role+'Service','AWS::ECS::Service',svc,DependsOn=['HttpsListener','GatewayRoute','DatabaseWriter'])
add('QueueDepthAlarm','AWS::CloudWatch::Alarm',{'Namespace':'AWS/SQS','MetricName':'ApproximateNumberOfMessagesVisible','Dimensions':[{'Name':'QueueName','Value':A('DeadLetterQueue','QueueName')}],'Statistic':'Maximum','Period':60,'EvaluationPeriods':1,'Threshold':0,'ComparisonOperator':'GreaterThanThreshold','TreatMissingData':'notBreaching','AlarmActions':[R('Notifications')]})
add('Budget','AWS::Budgets::Budget',{'Budget':{'BudgetName':S('${NamePrefix}-${Environment}-monthly'),'BudgetType':'COST','TimeUnit':'MONTHLY','BudgetLimit':{'Amount':R('MonthlyBudgetUsd'),'Unit':'USD'},'CostTypes':{'IncludeTax':True,'IncludeSubscription':True,'IncludeSupport':True}},'NotificationsWithSubscribers':[{'Notification':{'NotificationType':kind,'ComparisonOperator':'GREATER_THAN','Threshold':threshold,'ThresholdType':'PERCENTAGE'},'Subscribers':[{'SubscriptionType':'EMAIL','Address':R('NotificationEmail')}]} for kind,threshold in [('ACTUAL',80),('FORECASTED',100)]]})
# The topic only accepts this stack's CloudWatch alarms. The KMS key policy must also allow alarm delivery.
alarmArns=[A('QueueDepthAlarm','Arn')]+[A(role+'CpuAlarm','Arn') for role in ['Api','Gateway','Worker']]+[IF('RuntimeEnabled',A(role+'HeartbeatAlarm','Arn'),NO) for role in ['Api','Gateway','Worker']]
add('NotificationPolicy','AWS::SNS::TopicPolicy',{'Topics':[R('Notifications')],'PolicyDocument':policy([{'Effect':'Allow','Principal':{'Service':'cloudwatch.amazonaws.com'},'Action':'sns:Publish','Resource':R('Notifications'),'Condition':{'StringEquals':{'aws:SourceAccount':R('AWS::AccountId')},'ArnEquals':{'aws:SourceArn':alarmArns}}}])})
# Dedicated deployment role cannot edit IAM, infrastructure, task secrets, or stack policy.
serviceArns=[S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:service/${NamePrefix}-${Environment}/${NamePrefix}-${Environment}-'+x) for x in ['api','gateway','worker']]
taskArns=[S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${NamePrefix}-${Environment}-'+x+':*') for x in ['api','gateway','worker']]
taskArns.append(S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${NamePrefix}-${Environment}-compatibility:*'))
cluster=A('Database','DBClusterArn');clone=S('arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster:${NamePrefix}-${Environment}-rehearsal-*');cloneInstance=S('arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:db:${NamePrefix}-${Environment}-rehearsal-*');snapshot=S('arn:${AWS::Partition}:rds:${AWS::Region}:${AWS::AccountId}:cluster-snapshot:${NamePrefix}-${Environment}-release-*')
region={'StringEquals':{'aws:RequestedRegion':R('AWS::Region')}}
deployStatements=[allow(['ecs:DescribeServices','ecs:UpdateService'],serviceArns),allow(['ecs:DescribeTaskDefinition'],taskArns),allow(['ecs:RegisterTaskDefinition'],'*',Condition=region),allow(['ecs:DescribeTasks','ecs:ListTasks'], '*',Condition={'ArnEquals':{'ecs:cluster':A('Cluster','Arn')},**region}),allow(['ecs:TagResource'],taskArns,Condition={'StringEquals':{'ecs:CreateAction':'RegisterTaskDefinition'}}),allow(['iam:PassRole'],[A(role+k,'Arn') for role in ['Api','Gateway','Worker'] for k in ['TaskRole','ExecutionRole']],Condition={'StringEquals':{'iam:PassedToService':'ecs-tasks.amazonaws.com'}}),allow(['ecr:DescribeImages','ecr:BatchGetImage','ecr:GetDownloadUrlForLayer'],[R(role+'ImageRepositoryArn') for role in ['Api','Gateway','Worker']]),allow(['elasticloadbalancing:DescribeTargetHealth'],'*',Condition=region),allow(['cloudwatch:DescribeAlarms'],'*',Condition=region),allow(['dynamodb:DescribeTable','dynamodb:GetItem','dynamodb:PutItem','dynamodb:UpdateItem','dynamodb:DeleteItem'],A('DeploymentLocks','Arn')),allow(['rds:DescribeDBClusters','rds:DescribeDBInstances','rds:DescribeDBClusterSnapshots'],'*',Condition=region),allow(['rds:CreateDBClusterSnapshot'],[cluster,snapshot]),allow(['rds:RestoreDBClusterFromSnapshot'],[snapshot,clone,A('DbSubnetGroup','DBSubnetGroupArn')]),allow(['rds:CreateDBInstance','rds:DeleteDBInstance'],[clone,cloneInstance,A('DbSubnetGroup','DBSubnetGroupArn')]),allow(['rds:ModifyDBCluster','rds:DeleteDBCluster','rds:EnableHttpEndpoint'],clone),allow(['rds:AddTagsToResource'],[clone,cloneInstance,snapshot]),allow(['rds:ListTagsForResource'],[cluster,clone,cloneInstance,snapshot]),allow(['rds:DeleteDBClusterSnapshot'],snapshot),allow(['rds-data:ExecuteStatement','rds-data:BatchExecuteStatement','rds-data:BeginTransaction','rds-data:CommitTransaction','rds-data:RollbackTransaction'],[cluster,clone]),allow(['secretsmanager:GetSecretValue'],A('Database','MasterUserSecret.SecretArn')),allow(['secretsmanager:GetSecretValue'],S('arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!cluster-*'),Condition={'StringLike':{'aws:ResourceTag/aws:rds:primarydbclusterarn':clone}}),allow(['kms:Decrypt','kms:DescribeKey','kms:GenerateDataKey'],R('DataKmsKeyArn')),allow(['kms:CreateGrant'],R('DataKmsKeyArn'),Condition={'Bool':{'kms:GrantIsForAWSResource':'true'}})]
roleTrust=[{'Effect':'Allow','Principal':{'AWS':R('ControllerPrincipalArn')},'Action':'sts:AssumeRole'},IF('UseGitHubOidc',{'Effect':'Allow','Principal':{'Federated':R('GitHubOidcProviderArn')},'Action':'sts:AssumeRoleWithWebIdentity','Condition':{'StringEquals':{'token.actions.githubusercontent.com:aud':'sts.amazonaws.com','token.actions.githubusercontent.com:sub':S('repo:${GitHubRepository}:environment:${Environment}')}}},NO)]
add('DeploymentRole','AWS::IAM::Role',{'AssumeRolePolicyDocument':policy(roleTrust),'MaxSessionDuration':3600,'Policies':[{'PolicyName':'ExactEnvironmentRelease','PolicyDocument':policy(deployStatements)}],'Tags':tags})

for name in ['RehearsalDatabaseSecurityGroup','RehearsalTaskSecurityGroup']:
 add(name,'AWS::EC2::SecurityGroup',{'GroupDescription':'Isolated schema compatibility rehearsal','VpcId':R('VpcId'),'SecurityGroupEgress':[{'IpProtocol':'-1','CidrIp':'127.0.0.1/32'}],'Tags':tags})
add('RehearsalDbIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R('RehearsalDatabaseSecurityGroup'),'SourceSecurityGroupId':R('RehearsalTaskSecurityGroup'),'IpProtocol':'tcp','FromPort':5432,'ToPort':5432})
for logical,dest,port in [('Database','RehearsalDatabaseSecurityGroup',5432),('Endpoints','EndpointSecurityGroup',443)]:
 add('Rehearsal'+logical+'Egress','AWS::EC2::SecurityGroupEgress',{'GroupId':R('RehearsalTaskSecurityGroup'),'DestinationSecurityGroupId':R(dest),'IpProtocol':'tcp','FromPort':port,'ToPort':port})
add('RehearsalEndpointIngress','AWS::EC2::SecurityGroupIngress',{'GroupId':R('EndpointSecurityGroup'),'SourceSecurityGroupId':R('RehearsalTaskSecurityGroup'),'IpProtocol':'tcp','FromPort':443,'ToPort':443})
add('RehearsalS3Egress','AWS::EC2::SecurityGroupEgress',{'GroupId':R('RehearsalTaskSecurityGroup'),'DestinationPrefixListId':R('S3PrefixListId'),'IpProtocol':'tcp','FromPort':443,'ToPort':443})
add('RehearsalLogs','AWS::Logs::LogGroup',{'KmsKeyId':R('LogsKmsKeyArn'),'RetentionInDays':R('LogRetentionDays'),'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
add('RehearsalTaskRole','AWS::IAM::Role',{'AssumeRolePolicyDocument':trust,'Tags':tags})
add('RehearsalExecutionRole','AWS::IAM::Role',{'AssumeRolePolicyDocument':trust,'Policies':[{'PolicyName':'OnlyPullLogsAndDatabaseCredentials','PolicyDocument':policy([allow(['ecr:GetAuthorizationToken'],'*',Condition=region),allow(['ecr:BatchCheckLayerAvailability','ecr:GetDownloadUrlForLayer','ecr:BatchGetImage'],[R(role+'ImageRepositoryArn') for role in ['Api','Gateway','Worker']]),allow(['logs:CreateLogStream','logs:PutLogEvents'],A('RehearsalLogs','Arn')),allow(['secretsmanager:GetSecretValue'],[R(role+'DatabaseSecretArn') for role in ['Api','Gateway','Worker']]),allow(['kms:Decrypt'],R('DataKmsKeyArn'),Condition={'StringEquals':{'kms:ViaService':S('secretsmanager.${AWS::Region}.${AWS::URLSuffix}')}})])}],'Tags':tags})
deployStatements += [allow(['iam:PassRole'],[A('RehearsalTaskRole','Arn'),A('RehearsalExecutionRole','Arn')],Condition={'StringEquals':{'iam:PassedToService':'ecs-tasks.amazonaws.com'}}),allow(['ecs:RunTask'],S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${NamePrefix}-${Environment}-compatibility:*'),Condition={'ArnEquals':{'ecs:cluster':A('Cluster','Arn')},'StringEquals':{'aws:RequestTag/oxagen:purpose':'compatibility'},'StringLike':{'aws:RequestTag/oxagen:release':'?*'},'ForAllValues:StringEquals':{'aws:TagKeys':['oxagen:purpose','oxagen:release']}}),allow(['ecs:StopTask'],S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task/${NamePrefix}-${Environment}/*'),Condition={'StringEquals':{'aws:ResourceTag/oxagen:purpose':'compatibility'},'StringLike':{'aws:ResourceTag/oxagen:release':'?*'}}),allow(['ecs:TagResource'],S('arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task/${NamePrefix}-${Environment}/*'),Condition={'StringEquals':{'ecs:CreateAction':'RunTask','aws:RequestTag/oxagen:purpose':'compatibility'},'StringLike':{'aws:RequestTag/oxagen:release':'?*'},'ForAllValues:StringEquals':{'aws:TagKeys':['oxagen:purpose','oxagen:release']}}),allow(['secretsmanager:CreateSecret','secretsmanager:TagResource'],S('arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!cluster-*')),allow(['secretsmanager:DescribeSecret'],[A('Database','MasterUserSecret.SecretArn'),S('arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:rds!cluster-*')])]
O={'ClusterName':out(R('Cluster'),'ECS cluster name'),'ClusterArn':out(A('Cluster','Arn'),'ECS cluster ARN'),'DeploymentRoleArn':out(A('DeploymentRole','Arn'),'Only the configured environment release authority'),'LoadBalancerDnsName':out(A('LoadBalancer','DNSName'),'Create the declared hostname alias to this ALB'),'LoadBalancerHostedZoneId':out(A('LoadBalancer','CanonicalHostedZoneID'),'DNS alias target zone'),'HealthUrl':out(S('https://${PublicHostname}/health/ready'),'Hostname must resolve and be covered by certificate'),'GatewayHealthUrl':out(S('https://${PublicHostname}/gateway/health/ready'),'Gateway must handle the preserved path prefix'),'DatabaseClusterIdentifier':out(R('Database'),'Aurora cluster identifier'),'DatabaseClusterArn':out(cluster,'Aurora Data API authority'),'DatabaseEndpoint':out(A('Database','Endpoint.Address'),'Private PostgreSQL endpoint'),'DatabaseName':out('oxagen','Database name'),'DatabaseEngineVersion':out(R('PostgresEngineVersion'),'Pinned Aurora engine version; updates require reviewed maintenance'),'DatabaseMasterSecretArn':out(A('Database','MasterUserSecret.SecretArn'),'Trusted migration authority only; never mount into app tasks'),'DatabaseSubnetGroupName':out(R('DbSubnetGroup'),'Rehearsal restore subnet group'),'DatabaseSecurityGroupId':out(R('DatabaseSecurityGroup'),'Private DB ingress group'),'DataKmsKeyArn':out(R('DataKmsKeyArn'),'Encryption key for DB, records and deployment lock'),'PrivateSubnetIds':out({'Fn::Join':[',',R('PrivateSubnetIds')]},'Approved private task subnets'),'ArtifactBucketName':out(R('Artifacts'),'Encrypted, versioned tenant record objects'),'DeploymentLockTableName':out(R('DeploymentLocks'),'PK release_scope; no TTL: uncertain deployments keep their lock'),'RehearsalPrefix':out(S('${NamePrefix}-${Environment}-rehearsal-'),'Only this temporary DB prefix is mutable by deploy role'),'SnapshotPrefix':out(S('${NamePrefix}-${Environment}-release-'),'Only this release snapshot prefix is mutable by deploy role')}
for role in ['Api','Gateway','Worker']:
 O[role+'ImageRepositoryUri']=out(R(role+'ImageRepositoryUri'),role+' pinned image repository');O[role+'ImageRepositoryArn']=out(R(role+'ImageRepositoryArn'),role+' image repository ARN');O[role+'DatabaseSecretArn']=out(R(role+'DatabaseSecretArn'),role+' scoped database secret')
 for key,value in [('ServiceName',A(role+'Service','Name')),('ServiceArn',R(role+'Service')),('TaskDefinitionArn',R(role+'TaskDefinition')),('TaskRoleArn',A(role+'TaskRole','Arn')),('ExecutionRoleArn',A(role+'ExecutionRole','Arn')),('SecurityGroupId',R(role+'SecurityGroup')),('LogGroupName',R(role+'Logs'))]:O[role+key]=out(value,role+' '+key)
 if role!='Worker':O[role+'TargetGroupArn']=out(R(role+'TargetGroup'),role+' health target group')
for key in ['RehearsalDatabaseSecurityGroup','RehearsalTaskSecurityGroup']:O[key+'Id']=out(R(key),'Only the compatibility clone may use this scope')
O['RehearsalTaskRoleArn']=out(A('RehearsalTaskRole','Arn'),'No runtime data or provider permissions');O['RehearsalExecutionRoleArn']=out(A('RehearsalExecutionRole','Arn'),'Pull approved images, logs and scoped DB credentials only');O['RehearsalLogGroupName']=out(R('RehearsalLogs'),'Compatibility command logs');O['CompatibilityTaskFamily']=out(S('${NamePrefix}-${Environment}-compatibility'),'Only this task family can run as rehearsal')
env={**base,'Description':'Oxagen staging or production: private Fargate API/gateway/worker, Aurora PostgreSQL, encrypted records and bounded release authority. Requires existing approved network, keys, certificate, secret references and published image.','Parameters':P,'Conditions':C,'Rules':{'OidcRepositoryProvided':{'RuleCondition':{'Fn::Not':[{'Fn::Equals':[R('GitHubOidcProviderArn'),'']}]},'Assertions':[{'Assert':{'Fn::Not':[{'Fn::Equals':[R('GitHubRepository'),'']}]},'AssertDescription':'GitHub repository is required when an OIDC provider is configured.'}]}},'Resources':resources,'Outputs':O}
write('environment.json',env)

registry={'AWSTemplateFormatVersion':'2010-09-09','Description':'Create three immutable image repositories and ECR-only publication authority before the first service stack.','Parameters':{k:P[k] for k in ['NamePrefix','Environment','ControllerPrincipalArn','GitHubOidcProviderArn','GitHubRepository']},'Conditions':{'UseGitHubOidc':C['UseGitHubOidc']},'Resources':{},'Outputs':{},'Rules':env['Rules']}
registry['Parameters']['EcrKmsKeyArn']=param(AllowedPattern='arn:[^:]+:kms:[^:]+:[0-9]{12}:key/.+')
for role in ['Api','Gateway','Worker']:
 registry['Resources'][role+'Repository']=res('AWS::ECR::Repository',{'RepositoryName':S('${NamePrefix}/${Environment}/'+role.lower()),'ImageTagMutability':'IMMUTABLE','EncryptionConfiguration':{'EncryptionType':'KMS','KmsKey':R('EcrKmsKeyArn')},'EmptyOnDelete':False,'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
 registry['Outputs'][role+'RepositoryArn']=out(A(role+'Repository','Arn'),role+' exact ECR repository ARN');registry['Outputs'][role+'RepositoryUri']=out(A(role+'Repository','RepositoryUri'),role+' image destination');registry['Outputs'][role+'RepositoryName']=out(R(role+'Repository'),role+' repository name')
registry['Resources']['ArtifactPublisherRole']=res('AWS::IAM::Role',{'AssumeRolePolicyDocument':policy(roleTrust),'MaxSessionDuration':3600,'Policies':[{'PolicyName':'ThreeImmutableImageRepositories','PolicyDocument':policy([allow(['ecr:GetAuthorizationToken'],'*',Condition=region),allow(['ecr:BatchCheckLayerAvailability','ecr:InitiateLayerUpload','ecr:UploadLayerPart','ecr:CompleteLayerUpload','ecr:PutImage','ecr:DescribeRepositories','ecr:BatchGetImage','ecr:GetDownloadUrlForLayer','ecr:DescribeImages'],[A(role+'Repository','Arn') for role in ['Api','Gateway','Worker']])])}],'Tags':tags})
registry['Outputs']['ArtifactPublisherRoleArn']=out(A('ArtifactPublisherRole','Arn'),'ECR only; no ECS, database or deployment authority')
registry['Resources']['InfrastructureTemplates']=res('AWS::S3::Bucket',{'PublicAccessBlockConfiguration':{'BlockPublicAcls':True,'IgnorePublicAcls':True,'BlockPublicPolicy':True,'RestrictPublicBuckets':True},'OwnershipControls':{'Rules':[{'ObjectOwnership':'BucketOwnerEnforced'}]},'BucketEncryption':{'ServerSideEncryptionConfiguration':[{'ServerSideEncryptionByDefault':{'SSEAlgorithm':'aws:kms','KMSMasterKeyID':R('EcrKmsKeyArn')}}]},'VersioningConfiguration':{'Status':'Enabled'},'Tags':tags},DeletionPolicy='Retain',UpdateReplacePolicy='Retain')
registry['Resources']['TemplatePolicy']=res('AWS::S3::BucketPolicy',{'Bucket':R('InfrastructureTemplates'),'PolicyDocument':policy([{'Effect':'Deny','Principal':'*','Action':'s3:*','Resource':[A('InfrastructureTemplates','Arn'),S('${InfrastructureTemplates.Arn}/*')],'Condition':{'Bool':{'aws:SecureTransport':'false'}}}])})
registry['Outputs']['InfrastructureTemplateBucketName']=out(R('InfrastructureTemplates'),'Versioned private bucket for reviewed CloudFormation templates only')
write('registry.json',registry)

print(json.dumps({'registry_resources':len(registry['Resources']),'environment_resources':len(resources),'parameters':len(P),'outputs':len(O)}))
